"""Change stripe billing fields

Revision ID: 053bf6610506
Revises: 8ebd4fdd00d4
Create Date: 2025-06-04 14:26:31.793716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '053bf6610506'
down_revision: Union[str, None] = '8ebd4fdd00d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiwiq_billing_credit_purchase', sa.Column('stripe_checkout_id', sa.String(), nullable=True))
    op.drop_index('ix_kiwiq_billing_credit_purchase_stripe_payment_intent_id', table_name='kiwiq_billing_credit_purchase')
    op.create_index(op.f('ix_kiwiq_billing_credit_purchase_stripe_checkout_id'), 'kiwiq_billing_credit_purchase', ['stripe_checkout_id'], unique=True)
    op.drop_column('kiwiq_billing_credit_purchase', 'stripe_invoice_id')
    op.drop_column('kiwiq_billing_credit_purchase', 'stripe_payment_intent_id')
    op.drop_column('kiwiq_billing_org_subscription', 'stripe_subscription_item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiwiq_billing_org_subscription', sa.Column('stripe_subscription_item_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('kiwiq_billing_credit_purchase', sa.Column('stripe_payment_intent_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('kiwiq_billing_credit_purchase', sa.Column('stripe_invoice_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_kiwiq_billing_credit_purchase_stripe_checkout_id'), table_name='kiwiq_billing_credit_purchase')
    op.create_index('ix_kiwiq_billing_credit_purchase_stripe_payment_intent_id', 'kiwiq_billing_credit_purchase', ['stripe_payment_intent_id'], unique=True)
    op.drop_column('kiwiq_billing_credit_purchase', 'stripe_checkout_id')
    # ### end Alembic commands ###
