"""add external billing ID to Orgs

Revision ID: 0beed74259b7
Revises: 053bf6610506
Create Date: 2025-06-04 16:45:39.742211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0beed74259b7'
down_revision: Union[str, None] = '053bf6610506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiwiq_auth_org', sa.Column('external_billing_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_kiwiq_auth_org_external_billing_id'), 'kiwiq_auth_org', ['external_billing_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kiwiq_auth_org_external_billing_id'), table_name='kiwiq_auth_org')
    op.drop_column('kiwiq_auth_org', 'external_billing_id')
    # ### end Alembic commands ###
