"""Prefect RUN ID

Revision ID: 14d3bb2d76f0
Revises: 57a3531ac05d
Create Date: 2025-05-10 14:55:03.197708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '14d3bb2d76f0'
down_revision: Union[str, None] = '57a3531ac05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kw_wf_workflow_run', sa.Column('prefect_run_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kw_wf_workflow_run', 'prefect_run_id')
    # ### end Alembic commands ###
