"""Add Chat Thread model

Revision ID: 193e053ee14b
Revises: 72a4f76a4453
Create Date: 2025-05-19 11:51:42.752945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '193e053ee14b'
down_revision: Union[str, None] = '72a4f76a4453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kw_wf_chat_thread',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workflow_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thread_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['kiwiq_auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kw_wf_chat_thread_id'), 'kw_wf_chat_thread', ['id'], unique=False)
    op.create_index(op.f('ix_kw_wf_chat_thread_user_id'), 'kw_wf_chat_thread', ['user_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_chat_thread_workflow_name'), 'kw_wf_chat_thread', ['workflow_name'], unique=False)
    op.create_index(op.f('ix_kw_wf_chat_thread_workflow_version'), 'kw_wf_chat_thread', ['workflow_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kw_wf_chat_thread_workflow_version'), table_name='kw_wf_chat_thread')
    op.drop_index(op.f('ix_kw_wf_chat_thread_workflow_name'), table_name='kw_wf_chat_thread')
    op.drop_index(op.f('ix_kw_wf_chat_thread_user_id'), table_name='kw_wf_chat_thread')
    op.drop_index(op.f('ix_kw_wf_chat_thread_id'), table_name='kw_wf_chat_thread')
    op.drop_table('kw_wf_chat_thread')
    # ### end Alembic commands ###
