"""promotion code usage promo ID SET NULL constraint

Revision ID: 2d712715f78b
Revises: 8af5d85d3fa0
Create Date: 2025-06-25 16:51:26.898693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d712715f78b'
down_revision: Union[str, None] = '8af5d85d3fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kiwiq_billing_promotion_code_usage', 'promo_code_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('kiwiq_billing_promotion_code_usage_promo_code_id_fkey', 'kiwiq_billing_promotion_code_usage', type_='foreignkey')
    op.create_foreign_key(None, 'kiwiq_billing_promotion_code_usage', 'kiwiq_billing_promotion_code', ['promo_code_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kiwiq_billing_promotion_code_usage', type_='foreignkey')
    op.create_foreign_key('kiwiq_billing_promotion_code_usage_promo_code_id_fkey', 'kiwiq_billing_promotion_code_usage', 'kiwiq_billing_promotion_code', ['promo_code_id'], ['id'])
    op.alter_column('kiwiq_billing_promotion_code_usage', 'promo_code_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
