"""Initial revision: Auth

Revision ID: 3c171fa4f1eb
Revises: 
Create Date: 2025-04-07 02:32:26.064969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c171fa4f1eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiwiq_auth_org',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiwiq_auth_org_id'), 'kiwiq_auth_org', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_auth_org_name'), 'kiwiq_auth_org', ['name'], unique=False)
    op.create_table('kiwiq_auth_permission',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiwiq_auth_permission_id'), 'kiwiq_auth_permission', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_auth_permission_name'), 'kiwiq_auth_permission', ['name'], unique=True)
    op.create_table('kiwiq_auth_role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiwiq_auth_role_id'), 'kiwiq_auth_role', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_auth_role_name'), 'kiwiq_auth_role', ['name'], unique=True)
    op.create_table('kiwiq_auth_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('linkedin_id', sa.String(), nullable=True),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiwiq_auth_user_email'), 'kiwiq_auth_user', ['email'], unique=True)
    op.create_index(op.f('ix_kiwiq_auth_user_email_verification_token'), 'kiwiq_auth_user', ['email_verification_token'], unique=False)
    op.create_index(op.f('ix_kiwiq_auth_user_id'), 'kiwiq_auth_user', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_auth_user_is_active'), 'kiwiq_auth_user', ['is_active'], unique=False)
    op.create_index(op.f('ix_kiwiq_auth_user_is_superuser'), 'kiwiq_auth_user', ['is_superuser'], unique=False)
    op.create_index(op.f('ix_kiwiq_auth_user_is_verified'), 'kiwiq_auth_user', ['is_verified'], unique=False)
    op.create_index(op.f('ix_kiwiq_auth_user_linkedin_id'), 'kiwiq_auth_user', ['linkedin_id'], unique=True)
    op.create_table('kiwiq_auth_refresh_token',
    sa.Column('token', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['kiwiq_auth_user.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_kiwiq_auth_refresh_token_token'), 'kiwiq_auth_refresh_token', ['token'], unique=True)
    op.create_index(op.f('ix_kiwiq_auth_refresh_token_user_id'), 'kiwiq_auth_refresh_token', ['user_id'], unique=False)
    op.create_table('kiwiq_auth_role_permission_link',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['kiwiq_auth_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['kiwiq_auth_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('kiwiq_auth_user_org_role',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['kiwiq_auth_org.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['kiwiq_auth_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['kiwiq_auth_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kiwiq_auth_user_org_role')
    op.drop_table('kiwiq_auth_role_permission_link')
    op.drop_index(op.f('ix_kiwiq_auth_refresh_token_user_id'), table_name='kiwiq_auth_refresh_token')
    op.drop_index(op.f('ix_kiwiq_auth_refresh_token_token'), table_name='kiwiq_auth_refresh_token')
    op.drop_table('kiwiq_auth_refresh_token')
    op.drop_index(op.f('ix_kiwiq_auth_user_linkedin_id'), table_name='kiwiq_auth_user')
    op.drop_index(op.f('ix_kiwiq_auth_user_is_verified'), table_name='kiwiq_auth_user')
    op.drop_index(op.f('ix_kiwiq_auth_user_is_superuser'), table_name='kiwiq_auth_user')
    op.drop_index(op.f('ix_kiwiq_auth_user_is_active'), table_name='kiwiq_auth_user')
    op.drop_index(op.f('ix_kiwiq_auth_user_id'), table_name='kiwiq_auth_user')
    op.drop_index(op.f('ix_kiwiq_auth_user_email_verification_token'), table_name='kiwiq_auth_user')
    op.drop_index(op.f('ix_kiwiq_auth_user_email'), table_name='kiwiq_auth_user')
    op.drop_table('kiwiq_auth_user')
    op.drop_index(op.f('ix_kiwiq_auth_role_name'), table_name='kiwiq_auth_role')
    op.drop_index(op.f('ix_kiwiq_auth_role_id'), table_name='kiwiq_auth_role')
    op.drop_table('kiwiq_auth_role')
    op.drop_index(op.f('ix_kiwiq_auth_permission_name'), table_name='kiwiq_auth_permission')
    op.drop_index(op.f('ix_kiwiq_auth_permission_id'), table_name='kiwiq_auth_permission')
    op.drop_table('kiwiq_auth_permission')
    op.drop_index(op.f('ix_kiwiq_auth_org_name'), table_name='kiwiq_auth_org')
    op.drop_index(op.f('ix_kiwiq_auth_org_id'), table_name='kiwiq_auth_org')
    op.drop_table('kiwiq_auth_org')
    # ### end Alembic commands ###
