"""Prefect RUN ID convert to comma separated list

Revision ID: 4a54cad110c5
Revises: 14d3bb2d76f0
Create Date: 2025-05-10 17:13:01.080958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a54cad110c5'
down_revision: Union[str, None] = '14d3bb2d76f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kw_wf_workflow_run', sa.Column('prefect_run_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('kw_wf_workflow_run', 'prefect_run_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kw_wf_workflow_run', sa.Column('prefect_run_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('kw_wf_workflow_run', 'prefect_run_ids')
    # ### end Alembic commands ###
