"""workflow run workflow_id SET NULL

Revision ID: 8af5d85d3fa0
Revises: 5200095f9754
Create Date: 2025-06-25 16:34:02.911031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8af5d85d3fa0'
down_revision: Union[str, None] = '5200095f9754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('kw_wf_workflow_run_workflow_id_fkey', 'kw_wf_workflow_run', type_='foreignkey')
    op.create_foreign_key(None, 'kw_wf_workflow_run', 'kw_wf_workflow', ['workflow_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kw_wf_workflow_run', type_='foreignkey')
    op.create_foreign_key('kw_wf_workflow_run_workflow_id_fkey', 'kw_wf_workflow_run', 'kw_wf_workflow', ['workflow_id'], ['id'])
    # ### end Alembic commands ###
