"""Add parent workflow run ID field to WorkflowRun model

Revision ID: 94b83df59d39
Revises: caf9aa033f9c
Create Date: 2025-08-06 11:55:59.633804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94b83df59d39'
down_revision: Union[str, None] = 'caf9aa033f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kw_wf_workflow_run', sa.Column('parent_run_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_kw_wf_workflow_run_parent_run_id'), 'kw_wf_workflow_run', ['parent_run_id'], unique=False)
    op.create_foreign_key(None, 'kw_wf_workflow_run', 'kw_wf_workflow_run', ['parent_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kw_wf_workflow_run', type_='foreignkey')
    op.drop_index(op.f('ix_kw_wf_workflow_run_parent_run_id'), table_name='kw_wf_workflow_run')
    op.drop_column('kw_wf_workflow_run', 'parent_run_id')
    # ### end Alembic commands ###
