"""remove stripe_customer_id from OrganizationSubscription

Revision ID: 95ffa56cd948
Revises: 0beed74259b7
Create Date: 2025-06-04 16:48:16.383558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95ffa56cd948'
down_revision: Union[str, None] = '0beed74259b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kiwiq_billing_org_subscription_stripe_customer_id', table_name='kiwiq_billing_org_subscription')
    op.drop_column('kiwiq_billing_org_subscription', 'stripe_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiwiq_billing_org_subscription', sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_kiwiq_billing_org_subscription_stripe_customer_id', 'kiwiq_billing_org_subscription', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###
