"""add primary billing email to Org

Revision ID: a152f774891a
Revises: e818ee76261c
Create Date: 2025-06-08 12:53:44.767870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a152f774891a'
down_revision: Union[str, None] = 'e818ee76261c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiwiq_auth_org', sa.Column('primary_billing_email', sa.String(), nullable=True))
    op.create_index(op.f('ix_kiwiq_auth_org_primary_billing_email'), 'kiwiq_auth_org', ['primary_billing_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kiwiq_auth_org_primary_billing_email'), table_name='kiwiq_auth_org')
    op.drop_column('kiwiq_auth_org', 'primary_billing_email')
    # ### end Alembic commands ###
