"""Add data job model

Revision ID: a43f2dabdeea
Revises: 15f504cdf982
Create Date: 2025-06-28 14:59:46.114354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a43f2dabdeea'
down_revision: Union[str, None] = '15f504cdf982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiwiq_data_jobs_data_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'STARTED', 'COMPLETED', 'FAILED', 'CANCELLED', name='kiwiq_data_jobs_status_enum'), nullable=True),
    sa.Column('processed_timestamp_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_timestamp_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('processing_duration_seconds', sa.Float(), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kiwiq_data_jobs_data_job_status_created', 'kiwiq_data_jobs_data_job', ['status', 'created_at'], unique=False)
    op.create_index('idx_kiwiq_data_jobs_data_job_type_created', 'kiwiq_data_jobs_data_job', ['job_type', 'created_at'], unique=False)
    op.create_index('idx_kiwiq_data_jobs_data_job_type_status', 'kiwiq_data_jobs_data_job', ['job_type', 'status'], unique=False)
    op.create_index(op.f('ix_kiwiq_data_jobs_data_job_created_at'), 'kiwiq_data_jobs_data_job', ['created_at'], unique=False)
    op.create_index(op.f('ix_kiwiq_data_jobs_data_job_id'), 'kiwiq_data_jobs_data_job', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_data_jobs_data_job_job_type'), 'kiwiq_data_jobs_data_job', ['job_type'], unique=False)
    op.create_index(op.f('ix_kiwiq_data_jobs_data_job_processed_timestamp_end'), 'kiwiq_data_jobs_data_job', ['processed_timestamp_end'], unique=False)
    op.create_index(op.f('ix_kiwiq_data_jobs_data_job_processed_timestamp_start'), 'kiwiq_data_jobs_data_job', ['processed_timestamp_start'], unique=False)
    op.create_index(op.f('ix_kiwiq_data_jobs_data_job_status'), 'kiwiq_data_jobs_data_job', ['status'], unique=False)
    op.create_index(op.f('ix_kiwiq_data_jobs_data_job_updated_at'), 'kiwiq_data_jobs_data_job', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kiwiq_data_jobs_data_job_updated_at'), table_name='kiwiq_data_jobs_data_job')
    op.drop_index(op.f('ix_kiwiq_data_jobs_data_job_status'), table_name='kiwiq_data_jobs_data_job')
    op.drop_index(op.f('ix_kiwiq_data_jobs_data_job_processed_timestamp_start'), table_name='kiwiq_data_jobs_data_job')
    op.drop_index(op.f('ix_kiwiq_data_jobs_data_job_processed_timestamp_end'), table_name='kiwiq_data_jobs_data_job')
    op.drop_index(op.f('ix_kiwiq_data_jobs_data_job_job_type'), table_name='kiwiq_data_jobs_data_job')
    op.drop_index(op.f('ix_kiwiq_data_jobs_data_job_id'), table_name='kiwiq_data_jobs_data_job')
    op.drop_index(op.f('ix_kiwiq_data_jobs_data_job_created_at'), table_name='kiwiq_data_jobs_data_job')
    op.drop_index('idx_kiwiq_data_jobs_data_job_type_status', table_name='kiwiq_data_jobs_data_job')
    op.drop_index('idx_kiwiq_data_jobs_data_job_type_created', table_name='kiwiq_data_jobs_data_job')
    op.drop_index('idx_kiwiq_data_jobs_data_job_status_created', table_name='kiwiq_data_jobs_data_job')
    op.drop_table('kiwiq_data_jobs_data_job')
    # ### end Alembic commands ###
