"""Assets and User Resume Metadata service

Revision ID: caf9aa033f9c
Revises: a43f2dabdeea
Create Date: 2025-08-03 15:23:23.540410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'caf9aa033f9c'
down_revision: Union[str, None] = 'a43f2dabdeea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kw_wf_asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('managing_user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('app_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['managing_user_id'], ['kiwiq_auth_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['kiwiq_auth_org.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'asset_type', 'asset_name', name='kw_wf_asset_org_type_name_uc')
    )
    op.create_index(op.f('ix_kw_wf_asset_asset_name'), 'kw_wf_asset', ['asset_name'], unique=False)
    op.create_index(op.f('ix_kw_wf_asset_asset_type'), 'kw_wf_asset', ['asset_type'], unique=False)
    op.create_index(op.f('ix_kw_wf_asset_created_at'), 'kw_wf_asset', ['created_at'], unique=False)
    op.create_index(op.f('ix_kw_wf_asset_id'), 'kw_wf_asset', ['id'], unique=False)
    op.create_index(op.f('ix_kw_wf_asset_is_active'), 'kw_wf_asset', ['is_active'], unique=False)
    op.create_index(op.f('ix_kw_wf_asset_is_shared'), 'kw_wf_asset', ['is_shared'], unique=False)
    op.create_index(op.f('ix_kw_wf_asset_managing_user_id'), 'kw_wf_asset', ['managing_user_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_asset_org_id'), 'kw_wf_asset', ['org_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_asset_updated_at'), 'kw_wf_asset', ['updated_at'], unique=False)
    op.create_index('kw_wf_asset_org_managing_user_idx', 'kw_wf_asset', ['org_id', 'managing_user_id'], unique=False)
    op.create_index('kw_wf_asset_type_active_idx', 'kw_wf_asset', ['asset_type', 'is_active'], unique=False)
    op.create_table('kw_wf_user_app_resume_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workflow_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('entity_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('frontend_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('app_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['kw_wf_asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['kiwiq_auth_org.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['kw_wf_workflow_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['kiwiq_auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kw_wf_user_app_resume_metadata_asset_id'), 'kw_wf_user_app_resume_metadata', ['asset_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_user_app_resume_metadata_entity_tag'), 'kw_wf_user_app_resume_metadata', ['entity_tag'], unique=False)
    op.create_index(op.f('ix_kw_wf_user_app_resume_metadata_frontend_stage'), 'kw_wf_user_app_resume_metadata', ['frontend_stage'], unique=False)
    op.create_index(op.f('ix_kw_wf_user_app_resume_metadata_id'), 'kw_wf_user_app_resume_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_kw_wf_user_app_resume_metadata_org_id'), 'kw_wf_user_app_resume_metadata', ['org_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_user_app_resume_metadata_run_id'), 'kw_wf_user_app_resume_metadata', ['run_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_user_app_resume_metadata_user_id'), 'kw_wf_user_app_resume_metadata', ['user_id'], unique=False)
    op.create_index(op.f('ix_kw_wf_user_app_resume_metadata_workflow_name'), 'kw_wf_user_app_resume_metadata', ['workflow_name'], unique=False)
    op.create_index('kw_wf_user_app_resume_asset_idx', 'kw_wf_user_app_resume_metadata', ['asset_id', 'user_id'], unique=False)
    op.create_index('kw_wf_user_app_resume_org_user_idx', 'kw_wf_user_app_resume_metadata', ['org_id', 'user_id'], unique=False)
    op.create_index('kw_wf_user_app_resume_tag_idx', 'kw_wf_user_app_resume_metadata', ['entity_tag', 'user_id'], unique=False)
    op.create_index('kw_wf_user_app_resume_workflow_idx', 'kw_wf_user_app_resume_metadata', ['workflow_name', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('kw_wf_user_app_resume_workflow_idx', table_name='kw_wf_user_app_resume_metadata')
    op.drop_index('kw_wf_user_app_resume_tag_idx', table_name='kw_wf_user_app_resume_metadata')
    op.drop_index('kw_wf_user_app_resume_org_user_idx', table_name='kw_wf_user_app_resume_metadata')
    op.drop_index('kw_wf_user_app_resume_asset_idx', table_name='kw_wf_user_app_resume_metadata')
    op.drop_index(op.f('ix_kw_wf_user_app_resume_metadata_workflow_name'), table_name='kw_wf_user_app_resume_metadata')
    op.drop_index(op.f('ix_kw_wf_user_app_resume_metadata_user_id'), table_name='kw_wf_user_app_resume_metadata')
    op.drop_index(op.f('ix_kw_wf_user_app_resume_metadata_run_id'), table_name='kw_wf_user_app_resume_metadata')
    op.drop_index(op.f('ix_kw_wf_user_app_resume_metadata_org_id'), table_name='kw_wf_user_app_resume_metadata')
    op.drop_index(op.f('ix_kw_wf_user_app_resume_metadata_id'), table_name='kw_wf_user_app_resume_metadata')
    op.drop_index(op.f('ix_kw_wf_user_app_resume_metadata_frontend_stage'), table_name='kw_wf_user_app_resume_metadata')
    op.drop_index(op.f('ix_kw_wf_user_app_resume_metadata_entity_tag'), table_name='kw_wf_user_app_resume_metadata')
    op.drop_index(op.f('ix_kw_wf_user_app_resume_metadata_asset_id'), table_name='kw_wf_user_app_resume_metadata')
    op.drop_table('kw_wf_user_app_resume_metadata')
    op.drop_index('kw_wf_asset_type_active_idx', table_name='kw_wf_asset')
    op.drop_index('kw_wf_asset_org_managing_user_idx', table_name='kw_wf_asset')
    op.drop_index(op.f('ix_kw_wf_asset_updated_at'), table_name='kw_wf_asset')
    op.drop_index(op.f('ix_kw_wf_asset_org_id'), table_name='kw_wf_asset')
    op.drop_index(op.f('ix_kw_wf_asset_managing_user_id'), table_name='kw_wf_asset')
    op.drop_index(op.f('ix_kw_wf_asset_is_shared'), table_name='kw_wf_asset')
    op.drop_index(op.f('ix_kw_wf_asset_is_active'), table_name='kw_wf_asset')
    op.drop_index(op.f('ix_kw_wf_asset_id'), table_name='kw_wf_asset')
    op.drop_index(op.f('ix_kw_wf_asset_created_at'), table_name='kw_wf_asset')
    op.drop_index(op.f('ix_kw_wf_asset_asset_type'), table_name='kw_wf_asset')
    op.drop_index(op.f('ix_kw_wf_asset_asset_name'), table_name='kw_wf_asset')
    op.drop_table('kw_wf_asset')
    # ### end Alembic commands ###
