"""add receipt field to credit purchase

Revision ID: e31a17559edb
Revises: 95ffa56cd948
Create Date: 2025-06-04 19:08:17.398172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e31a17559edb'
down_revision: Union[str, None] = '95ffa56cd948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiwiq_billing_credit_purchase', sa.Column('receipt_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kiwiq_billing_credit_purchase', 'receipt_url')
    # ### end Alembic commands ###
