"""add stripe events model

Revision ID: e818ee76261c
Revises: e31a17559edb
Create Date: 2025-06-05 09:32:10.906473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e818ee76261c'
down_revision: Union[str, None] = 'e31a17559edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiwiq_billing_stripe_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stripe_event_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('api_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processed_successfully', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kiwiq_billing_stripe_event_created_type', 'kiwiq_billing_stripe_event', ['created_at', 'event_type'], unique=False)
    op.create_index('idx_kiwiq_billing_stripe_event_livemode_type', 'kiwiq_billing_stripe_event', ['livemode', 'event_type'], unique=False)
    op.create_index('idx_kiwiq_billing_stripe_event_org_type', 'kiwiq_billing_stripe_event', ['org_id', 'event_type'], unique=False)
    op.create_index('idx_kiwiq_billing_stripe_event_plan_type', 'kiwiq_billing_stripe_event', ['plan_id', 'event_type'], unique=False)
    op.create_index('idx_kiwiq_billing_stripe_event_processed', 'kiwiq_billing_stripe_event', ['processed_successfully', 'created_at'], unique=False)
    op.create_index('idx_kiwiq_billing_stripe_event_type_timestamp', 'kiwiq_billing_stripe_event', ['event_type', 'event_timestamp'], unique=False)
    op.create_index('idx_kiwiq_billing_stripe_event_user_type', 'kiwiq_billing_stripe_event', ['user_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_stripe_event_created_at'), 'kiwiq_billing_stripe_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_stripe_event_event_timestamp'), 'kiwiq_billing_stripe_event', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_stripe_event_event_type'), 'kiwiq_billing_stripe_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_stripe_event_id'), 'kiwiq_billing_stripe_event', ['id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_stripe_event_livemode'), 'kiwiq_billing_stripe_event', ['livemode'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_stripe_event_org_id'), 'kiwiq_billing_stripe_event', ['org_id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_stripe_event_plan_id'), 'kiwiq_billing_stripe_event', ['plan_id'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_stripe_event_processed_successfully'), 'kiwiq_billing_stripe_event', ['processed_successfully'], unique=False)
    op.create_index(op.f('ix_kiwiq_billing_stripe_event_stripe_event_id'), 'kiwiq_billing_stripe_event', ['stripe_event_id'], unique=True)
    op.create_index(op.f('ix_kiwiq_billing_stripe_event_user_id'), 'kiwiq_billing_stripe_event', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kiwiq_billing_stripe_event_user_id'), table_name='kiwiq_billing_stripe_event')
    op.drop_index(op.f('ix_kiwiq_billing_stripe_event_stripe_event_id'), table_name='kiwiq_billing_stripe_event')
    op.drop_index(op.f('ix_kiwiq_billing_stripe_event_processed_successfully'), table_name='kiwiq_billing_stripe_event')
    op.drop_index(op.f('ix_kiwiq_billing_stripe_event_plan_id'), table_name='kiwiq_billing_stripe_event')
    op.drop_index(op.f('ix_kiwiq_billing_stripe_event_org_id'), table_name='kiwiq_billing_stripe_event')
    op.drop_index(op.f('ix_kiwiq_billing_stripe_event_livemode'), table_name='kiwiq_billing_stripe_event')
    op.drop_index(op.f('ix_kiwiq_billing_stripe_event_id'), table_name='kiwiq_billing_stripe_event')
    op.drop_index(op.f('ix_kiwiq_billing_stripe_event_event_type'), table_name='kiwiq_billing_stripe_event')
    op.drop_index(op.f('ix_kiwiq_billing_stripe_event_event_timestamp'), table_name='kiwiq_billing_stripe_event')
    op.drop_index(op.f('ix_kiwiq_billing_stripe_event_created_at'), table_name='kiwiq_billing_stripe_event')
    op.drop_index('idx_kiwiq_billing_stripe_event_user_type', table_name='kiwiq_billing_stripe_event')
    op.drop_index('idx_kiwiq_billing_stripe_event_type_timestamp', table_name='kiwiq_billing_stripe_event')
    op.drop_index('idx_kiwiq_billing_stripe_event_processed', table_name='kiwiq_billing_stripe_event')
    op.drop_index('idx_kiwiq_billing_stripe_event_plan_type', table_name='kiwiq_billing_stripe_event')
    op.drop_index('idx_kiwiq_billing_stripe_event_org_type', table_name='kiwiq_billing_stripe_event')
    op.drop_index('idx_kiwiq_billing_stripe_event_livemode_type', table_name='kiwiq_billing_stripe_event')
    op.drop_index('idx_kiwiq_billing_stripe_event_created_type', table_name='kiwiq_billing_stripe_event')
    op.drop_table('kiwiq_billing_stripe_event')
    # ### end Alembic commands ###
