"""

Flow: 
1. input node -> load_all_context_docs and load_draft_posts
2. [load_all_context_docs, load_draft_posts] -> construct_initial_concepts_prompt (enable_node_fan_in true)
3. construct_initial_concepts_prompt -> generate_content
4. generate_content -> store_customer_data
5. store_customer_data -> capture_user_choice
5. capture_user_choice -> route_on_user_choice
6. route_on_user_choice -> construct_concepts_regeneration_prompt [selection: regenerate concepts]
7. route_on_user_choice -> output_node [selection: Go back to initial ideas brief generation]
8. route_on_user_choice -> filter_selected_concepts [selection: select list of concepts]
9. construct_concepts_regeneration_prompt -> generate_content (concepts regeneration loop, generate_content reads message_history from state)
10. filter_selected_concepts -> construct_update_content_brief_prompt
11. construct_update_content_brief_prompt -> generated_updated_content_brief
12. generated_updated_content_brief -> save_updated_content_brief
13. save_updated_content_brief -> output_node
"""

import asyncio
import logging
from typing import Dict, Any, Optional, List, Union, ClassVar, Type
import json
from enum import Enum

# Using Pydantic for easier schema generation
from pydantic import BaseModel, Field

# Internal dependencies
from kiwi_client.test_run_workflow_client import (
    run_workflow_test,
    SetupDocInfo,
    CleanupDocInfo
)
from kiwi_client.schemas.workflow_constants import WorkflowRunStatus

# --- Workflow Configuration Constants ---
# Namespaces and storage
USER_PROFILES_NAMESPACE = "user_profiles"
USER_DNA_DOCNAME = "user_dna_doc"
USER_PREFERENCES_DOCNAME = "user_preferences_doc"
GENERATED_STRATEGY_NAMESPACE = "generated_strategy"
STRATEGY_DOCS_NAMESPACE = "strategy_docs"
CONTENT_STRATEGY_DOCNAME = "content_strategy_doc_{item}"
GENERATED_STRATEGY_DOCNAME_PATTERN = "content_strategy_{item}"

# LLM Configuration
LLM_PROVIDER = "openai"
GENERATION_MODEL = "gpt-4.1"
LLM_TEMPERATURE = 1
LLM_MAX_TOKENS = 4000


### SAVE DOCUMENT CONFIG ###
SAVE_DOC_NAMESPACE = GENERATED_STRATEGY_NAMESPACE
SAVE_DOC_DOCNAME_PATTERN = GENERATED_STRATEGY_DOCNAME_PATTERN
SAVE_DOCNAME_INPUT_FIELD = "entity_username"
SAVE_DOC_FILENAME_CONFIG = {
    "filename_config": {
        "static_namespace": SAVE_DOC_NAMESPACE,
        "input_docname_field": SAVE_DOCNAME_INPUT_FIELD, # Field in node's input containing the value
        "input_docname_field_pattern": SAVE_DOC_DOCNAME_PATTERN  # 'item' here will be the value of entity_name
    }
}
SAVE_DOC_GLOBAL_VERSIONING = {
    "is_versioned": True,
    "operation": "upsert_versioned", # Must not exist yet
    # "version": "generated_draft" # Name the initial version
}
########################


### GENERATION SCHEMA ###
# --- Pydantic Schemas for LLM Outputs ---
class ContentTopicMixItem(BaseModel):
    """
    Represents a single content topic with its recommended percentage.
    """
    topic_name: str = Field(..., description="Name of the content topic (e.g., 'thought leadership', 'industry news').")
    percentage: float = Field(..., description="Recommended percentage for this topic (e.g., 40.0).")

class ContentFormatMixItem(BaseModel):
    """
    Represents a single content format with its recommended percentage.
    """
    format_name: str = Field(..., description="Name of the content format (e.g., 'text posts', 'carousels', 'videos').")
    percentage: float = Field(..., description="Recommended percentage for this format (e.g., 30.0).")

class ContentMixSchema(BaseModel):
    """
    Defines the structure for content distribution recommendations by topic and format.
    """
    topic_mix: List[ContentTopicMixItem] = Field(
        ..., 
        description="Distribution of content by topic type with percentages."
    )
    format_mix: List[ContentFormatMixItem] = Field(
        ..., 
        description="Distribution of content by format type with percentages."
    )
    
class PostingScheduleSchema(BaseModel):
    """
    Defines the structure for a posting schedule recommendation.
    """
    frequency: str = Field(..., description="How often to post (e.g., 'daily', 'twice weekly', 'weekly').")
    best_days: List[str] = Field(..., description="Best days of the week to post (e.g., ['Monday', 'Thursday']).")
    best_times: List[str] = Field(..., description="Best times of day to post (e.g., ['8:00 AM', '5:30 PM']).")
    content_mix: ContentMixSchema = Field(
        ..., 
        description="Recommended mix of content by topics and formats with percentages."
    )
    consistency_notes: str = Field(..., description="Notes on maintaining posting consistency and audience expectations.")

class ContentStrategySchema(BaseModel):
    """
    Defines the structure for a single content strategy generated by the LLM.
    """
    target_audience: str = Field(..., description="The intended audience for this content.")
    content_purpose: str = Field(..., description="The goal or objective of the content (educational, inspirational, etc.).")
    content_format: str = Field(..., description="The format of the content (article, post, carousel, etc.).")
    tone_and_style: str = Field(..., description="The tone and writing style for the content.")
    relevant_trends: List[str] = Field(..., description="Current industry trends relevant to the content.")
    key_statistics: List[str] = Field(..., description="Important statistics to support the content.")
    posting_schedule: PostingScheduleSchema = Field(..., description="Detailed posting schedule recommendations.")

GENERATION_SCHEMA = ContentStrategySchema.model_json_schema()
########################

### USER PROMPT TEMPLATE ###
USER_PROMPT_TEMPLATE = """Develop a comprehensive LinkedIn content strategy.

LinkedIn Profile to create strategy for: {entity_username}

**Strategic Framework:**
- Content Methodology: {content_methodology}
- Implementation Guidelines: {methodology_implementation}

**User Information:**
- Professional Profile: {user_dna}
- Content Preferences: {user_preferences}

**Task:**
Create 3 distinct content strategy concepts for this LinkedIn profile.
Each strategy should include target audience, content purpose, format recommendations, 
tone guidelines, relevant industry trends, and key statistics to leverage.
Provide diverse strategies that align with the user's professional goals and audience.

Respond ONLY with the JSON object matching the specified schema.
"""

USER_PROMPT_TEMPLATE_VARIABLES = {
    "user_dna": None,
    "content_methodology": None,
    "user_preferences": None,
    "methodology_implementation": None,
    "entity_username": None
}

USER_PROMPT_TEMPLATE_CONSTRUCT_OPTIONS = {
    "user_dna": "user_dna",
    "content_methodology": "content_methodology",
    "methodology_implementation": "methodology_implementation",
    "user_preferences": "user_preferences",
    "entity_username": "entity_username"
}
##############################

### SYSTEM PROMPT TEMPLATE ###
SYSTEM_PROMPT_TEMPLATE = "You are a strategic LinkedIn content consultant specializing in professional branding and audience growth. Develop 3-4 comprehensive content strategy options tailored to the user's professional background and goals. Each strategy should maximize engagement and thought leadership positioning. Respond strictly with the JSON output conforming to the schema: ```json\n{schema}\n```"

SYSTEM_PROMPT_TEMPLATE_VARIABLES = {
    "schema": GENERATION_SCHEMA
}

SYSTEM_PROMPT_TEMPLATE_CONSTRUCT_OPTIONS = {}
##############################

### EDGES CONFIG ###
field_mappings_from_state_to_prompt_constructor = [
    { "src_field": "user_preferences", "dst_field": "user_preferences"},
    { "src_field": "methodology_implementation", "dst_field": "methodology_implementation" },
    { "src_field": "content_methodology", "dst_field": "content_methodology" },
    { "src_field": "user_dna", "dst_field": "user_dna" },
    { "src_field": "entity_username", "dst_field": "entity_username" },
]

field_mappings_from_input_to_state = [
    { "src_field": "customer_context_doc_configs", "dst_field": "customer_context_doc_configs" },
    { "src_field": "entity_username", "dst_field": "entity_username" },
]

field_mappings_from_input_to_load_all_context_docs = [
    { "src_field": "customer_context_doc_configs", "dst_field": "customer_context_doc_configs" },
    { "src_field": "entity_username", "dst_field": "entity_username" },
]

field_mappings_from_load_all_context_docs_to_state = [
    { "src_field": "user_dna", "dst_field": "user_dna"},
    { "src_field": "user_preferences", "dst_field": "user_preferences"},
    { "src_field": "methodology_implementation", "dst_field": "methodology_implementation"},
    { "src_field": "content_methodology", "dst_field": "content_methodology"},
]

field_mappings_from_state_to_store_customer_data = [
    { "src_field": "entity_username", "dst_field": "entity_username"}
]

#############

### INPUTS ###

INPUT_FIELDS = {
    "customer_context_doc_configs": {
        "type": "list",
        "required": True,
        "description": "List of document identifiers (namespace/docname pairs) for customer context like DNA, strategy docs."
    },
    "entity_username": { "type": "str", "required": True, "description": "Name of the entity to generate strategy for."},
    # "entity_name": {"type": "str", "required": True},
}

INPUT_DOCS_TO_BE_LOADED_IN_WORKFLOW = [
    {
        "filename_config": {
            "static_namespace": USER_PROFILES_NAMESPACE, 
            "static_docname": USER_DNA_DOCNAME,
        },
        "output_field_name": "user_dna",
        "is_shared": False,
        "is_system_entity": False
    },
    {
        "filename_config": {
            "static_namespace": USER_PROFILES_NAMESPACE, 
            "static_docname": USER_PREFERENCES_DOCNAME,
        },
        "output_field_name": "user_preferences",
        "is_shared": False,
        "is_system_entity": False
    },
    {
        "filename_config": {
            "static_namespace": STRATEGY_DOCS_NAMESPACE,
            "static_docname": "methodology_implementation_ai_copilot",
        },
        "output_field_name": "methodology_implementation",
        "is_shared": True,
        "is_system_entity": True
    },
    {
        "filename_config": {
            "static_namespace": STRATEGY_DOCS_NAMESPACE,
            "static_docname": "building_blocks_content_methodology",
        },
        "output_field_name": "content_methodology",
        "is_shared": False,
        "is_system_entity": True
    },
]

##############


workflow_graph_schema = {
  "nodes": {
        # --- 1. Input Node ---
        "input_node": {
            "node_id": "input_node",
            "node_name": "input_node",
            "node_config": {},
            "dynamic_output_schema": {
                    "fields": INPUT_FIELDS
            }
                # Outputs: user_id, weeks_to_generate, customer_context_doc_configs, past_context_posts_limit -> $graph_state
        },

        # --- 2. Load Customer Context Documents and Scraped Posts (Single Node) ---
        "load_all_context_docs": {
            "node_id": "load_all_context_docs",
            "node_name": "load_customer_data",
            "node_config": {
                # Configure to load multiple documents based on the input list
                "load_configs_input_path": "customer_context_doc_configs", # Use the list from input node
                # Global defaults (can be overridden if needed per doc type via input structure)
                "global_is_shared": False,
                "global_is_system_entity": False,
                # "global_version_config": {"version": "default"},
                "global_schema_options": {"load_schema": False},
            },
        },

        # --- 9. Construct Brief Prompt (Inside Map Branch) ---
        "construct_prompt": {
            "node_id": "construct_prompt",
            "node_name": "prompt_constructor",
            "enable_node_fan_in": True,  # Wait for all data loads before proceeding
            "node_config": {
                "prompt_templates": {
                    "user_prompt": {
                        "id": "user_prompt",
                        "template": USER_PROMPT_TEMPLATE,
                        "variables": USER_PROMPT_TEMPLATE_VARIABLES,
                        "construct_options": USER_PROMPT_TEMPLATE_CONSTRUCT_OPTIONS
                    },
                    "system_prompt": {
                        "id": "system_prompt",
                        "template": SYSTEM_PROMPT_TEMPLATE,
                        "variables": SYSTEM_PROMPT_TEMPLATE_VARIABLES,
                        "construct_options": SYSTEM_PROMPT_TEMPLATE_CONSTRUCT_OPTIONS
                    }
                }
            }
        },

        # --- 10. Generate Brief (LLM - Inside Map Branch) ---
        "generate_content": {
            "node_id": "generate_content",
            "node_name": "llm",
            "node_config": {
                "llm_config": {
                    "model_spec": {"provider": LLM_PROVIDER, "model": GENERATION_MODEL},
                    "temperature": LLM_TEMPERATURE,
                    "max_tokens": LLM_MAX_TOKENS
                },
                "output_schema": {
                    "schema_definition": GENERATION_SCHEMA
                },
            }
        },

        # --- 5. Store Concepts ---
        "store_customer_data": {
            "node_id": "store_customer_data",
            "node_name": "store_customer_data",
            "node_config": {
                    "global_versioning": SAVE_DOC_GLOBAL_VERSIONING,
                "store_configs": [
                {
                    "input_field_path": "structured_output", # Field name in node input containing the value to save
                    "target_path": SAVE_DOC_FILENAME_CONFIG
                }
                ]
            }
            },


        # --- 12. Output Node ---
        "output_node": {
            "node_id": "output_node",
            "node_name": "output_node",
            "node_config": {},
            # "dynamic_input_schema": { # Define expected final inputs
            #     "fields": {
            #         "final_briefs_list": { "type": "list", "required": True, "description": "The complete list of generated content briefs." },
            #         "brief_paths_processed": { "type": "list", "required": False, "description": "Confirmation/path from the storage operation." }
            #     }
            # }
            # Reads: updated_brief (mapped to final_briefs_list), paths_processed (mapped to save_confirmation)
        },

    },

    # --- Edges Defining Data Flow ---
    "edges": [
        # --- Initial Setup ---
        # Input -> State: Store initial inputs globally
        { "src_node_id": "input_node", "dst_node_id": "$graph_state", "mappings": field_mappings_from_input_to_state
        },
        
        # Input -> Load operations
        { "src_node_id": "input_node", "dst_node_id": "load_all_context_docs", "mappings": field_mappings_from_input_to_load_all_context_docs, "description": "Trigger context docs loading."
        },


        # --- State Updates from Loaders ---
        { "src_node_id": "load_all_context_docs", "dst_node_id": "$graph_state", "mappings": field_mappings_from_load_all_context_docs_to_state
        },

        # --- Trigger Initial Concept Generation ---
        { "src_node_id": "load_all_context_docs", "dst_node_id": "construct_prompt" },

        # --- Mapping State to Initial Concepts Prompt ---
        { "src_node_id": "$graph_state", "dst_node_id": "construct_prompt", "mappings": field_mappings_from_state_to_prompt_constructor
        },

        # --- Construct Prompt → Generate Concepts ---
        { "src_node_id": "construct_prompt", "dst_node_id": "generate_content", "mappings": [
            { "src_field": "user_prompt", "dst_field": "user_prompt"},
            { "src_field": "system_prompt", "dst_field": "system_prompt"}
          ], "description": "Send prompts to LLM for concept generation."
        },

        # --- State -> Generate Concepts ---
        { "src_node_id": "$graph_state", "dst_node_id": "generate_content", "mappings": [
            { "src_field": "messages_history", "dst_field": "messages_history"}
          ]
        },

        # # --- Generate Concepts -> Store & State ---
        # { "src_node_id": "generate_content", "dst_node_id": "$graph_state", "mappings": [
        #     { "src_field": "structured_output", "dst_field": "current_generated_concepts"},
        #     { "src_field": "current_messages", "dst_field": "messages_history"}
        #   ]
        # },

        { "src_node_id": "generate_content", "dst_node_id": "store_customer_data", "mappings": [
            { "src_field": "structured_output", "dst_field": "structured_output"},
          ]
        },

        { "src_node_id": "generate_content", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "structured_output", "dst_field": "generated_output"},
          ]
        },

        # --- State -> Store Concepts ---
        { "src_node_id": "$graph_state", "dst_node_id": "store_customer_data", "mappings": field_mappings_from_state_to_store_customer_data
        },

        # --- Store Concepts -> User Choice ---
        { "src_node_id": "store_customer_data", "dst_node_id": "output_node", "mappings": [
            { "src_field": "paths_processed", "dst_field": "paths_processed"}
          ]
        },

        # --- State -> User Choice ---
        { "src_node_id": "$graph_state", "dst_node_id": "output_node", "mappings": [
            { "src_field": "generated_output", "dst_field": "generated_output"}
          ]
        },
    ],

    # --- Define Start and End ---
    "input_node_id": "input_node",
    "output_node_id": "output_node",

    # --- State Reducers ---
    "metadata": {
        "$graph_state": {
            "reducer": {
                # NOTE: If you set collect_values reducer here, it distorts / nests the concepts structure and fails the FILTER NODE!
                # "current_generated_concepts": "collect_values",
                # "messages_history": "add_messages"
            }
        }
    }
}

# --- Test Execution Logic ---
async def main_test_idea_to_brief_workflow():
    """
    Test for Idea to Brief Workflow.
    """
    test_name = "Idea to Brief Workflow Test"
    print(f"--- Starting {test_name} --- ")

    # Example Inputs
    test_context_docs = INPUT_DOCS_TO_BE_LOADED_IN_WORKFLOW
    
    entity_username = "test_entity"
    
    test_inputs = {
        "customer_context_doc_configs": test_context_docs,
        "entity_username": entity_username
    }

    # Define setup documents
    setup_docs: List[SetupDocInfo] = [
        {
            'namespace': USER_PROFILES_NAMESPACE, 
            'docname': USER_DNA_DOCNAME,
            'initial_data': {
                "professional_background": "Marketing executive",
                "expertise_areas": ["Digital Marketing", "Brand Strategy"],
                "target_audience": "Marketing professionals",
                "personal_style": "Conversational but authoritative"
            }, 
            'is_versioned': False, 
            'is_shared': False,
            'initial_version': None,
            'is_system_entity': False
        },
        {
            'namespace': USER_PROFILES_NAMESPACE, 
            'docname': USER_PREFERENCES_DOCNAME,
            'initial_data': {
                "posts_per_week": 2,
                "preferred_posting_days": ["Monday", "Thursday"],
                "preferred_topics": ["Leadership", "Marketing Trends"],
                "content_tone": "Professional"
            }, 
            'is_versioned': False, 
            'is_shared': False,
            'initial_version': None,
            'is_system_entity': False
        },
        {
            # NOTE: this can only be created by a superuser!
            'namespace': STRATEGY_DOCS_NAMESPACE,
            'docname': "methodology_implementation_ai_copilot",
            'initial_data': {
                "methodology_name": "AI Copilot Content Strategy",
                "implementation_steps": [
                    "Analyze user DNA and preferences",
                    "Generate content strategy aligned with user goals",
                    "Create content briefs based on strategy",
                    "Develop multiple content concepts for review"
                ],
                "best_practices": [
                    "Maintain consistent brand voice",
                    "Focus on audience pain points",
                    "Incorporate industry trends",
                    "Balance educational and promotional content"
                ]
            },
            'is_versioned': False,
            'is_shared': True,
            'initial_version': None,
            'is_system_entity': True
        },
        {
            # NOTE: this can only be created by a superuser!
            'namespace': STRATEGY_DOCS_NAMESPACE,
            'docname': "building_blocks_content_methodology",
            'initial_data': {
                "core_building_blocks": [
                    "Audience analysis",
                    "Content pillars",
                    "Content formats",
                    "Distribution channels",
                    "Performance metrics"
                ],
                "implementation_framework": {
                    "phase_1": "Discovery and analysis",
                    "phase_2": "Strategy development",
                    "phase_3": "Content creation",
                    "phase_4": "Distribution and promotion",
                    "phase_5": "Measurement and optimization"
                },
                "success_indicators": [
                    "Engagement rate",
                    "Conversion metrics",
                    "Audience growth",
                    "Content consistency"
                ]
            },
            'is_versioned': False,
            'is_shared': True,
            'initial_version': None,
            'is_system_entity': True
        }
    ]

    # Define cleanup docs
    cleanup_docs: List[CleanupDocInfo] = [
        {'namespace': USER_PROFILES_NAMESPACE, 'docname': USER_DNA_DOCNAME, 'is_versioned': False, 'is_shared': False, 'is_system_entity': False},
        {'namespace': USER_PROFILES_NAMESPACE, 'docname': USER_PREFERENCES_DOCNAME, 'is_versioned': False, 'is_shared': False, 'is_system_entity': False},
        {'namespace': STRATEGY_DOCS_NAMESPACE, 'docname': CONTENT_STRATEGY_DOCNAME.format(item=entity_username), 'is_versioned': False, 'is_shared': False, 'is_system_entity': False},
        {'namespace': STRATEGY_DOCS_NAMESPACE, 'docname': "methodology_implementation_ai_copilot", 'is_versioned': False, 'is_shared': True, 'is_system_entity': True},
        {'namespace': STRATEGY_DOCS_NAMESPACE, 'docname': "building_blocks_content_methodology", 'is_versioned': False, 'is_shared': True, 'is_system_entity': True},
    ]

    # Predefined HITL inputs
    predefined_hitl_inputs = [
        # {
        #     "approval_status": "select_concepts",  # "regenerate", "restart_from_idea_generation"
        #     "selected_concepts": ["concept_1", "concept_2"],
        # }
        # feedback_text  ;  
    ]
    # VALID HUMAN INPUTS TYPE TO CONSOLE DIRECTLY, ENSURE SELECTED ID IS EXACT MATCH TO GENERATED!
    # {"approval_status": "select_concepts", "selected_concepts": ["concept_004"]}
    # {"approval_status": "regenerate"}
    # {"approval_status": "restart_from_idea_generation"}
    # Output validation function
    async def validate_content_strategy_output(outputs):
        """
        Validates the output from the content strategy workflow against expected schema.
        
        Args:
            outputs: The workflow output dictionary to validate
            
        Returns:
            bool: True if validation passes, raises AssertionError otherwise
        """
        assert outputs is not None, "Validation Failed: Workflow returned no outputs."
        assert 'generated_output' in outputs, "Validation Failed: 'generated_output' missing."
        assert 'paths_processed' in outputs, "Validation Failed: 'paths_processed' missing."
        
        # Validate the content structure
        if 'generated_output' in outputs:
            strategy = outputs['generated_output']
            
            # Validate strategy structure based on ContentStrategySchema
            assert 'target_audience' in strategy, "Strategy is missing 'target_audience' field"
            assert 'content_purpose' in strategy, "Strategy is missing 'content_purpose' field"
            assert 'content_format' in strategy, "Strategy is missing 'content_format' field"
            assert 'tone_and_style' in strategy, "Strategy is missing 'tone_and_style' field"
            assert 'relevant_trends' in strategy, "Strategy is missing 'relevant_trends' field"
            assert isinstance(strategy['relevant_trends'], list), "'relevant_trends' should be a list"
            assert 'key_statistics' in strategy, "Strategy is missing 'key_statistics' field"
            assert isinstance(strategy['key_statistics'], list), "'key_statistics' should be a list"
            
            # Validate posting schedule structure
            assert 'posting_schedule' in strategy, "Strategy is missing 'posting_schedule' field"
            posting_schedule = strategy['posting_schedule']
            assert 'frequency' in posting_schedule, "Posting schedule is missing 'frequency' field"
            assert 'best_days' in posting_schedule, "Posting schedule is missing 'best_days' field"
            assert isinstance(posting_schedule['best_days'], list), "'best_days' should be a list"
            assert 'best_times' in posting_schedule, "Posting schedule is missing 'best_times' field"
            assert isinstance(posting_schedule['best_times'], list), "'best_times' should be a list"
            assert 'content_mix' in posting_schedule, "Posting schedule is missing 'content_mix' field"
            assert 'consistency_notes' in posting_schedule, "Posting schedule is missing 'consistency_notes' field"
            
            # Validate content mix structure
            content_mix = posting_schedule['content_mix']
            assert 'topic_mix' in content_mix, "Content mix is missing 'topic_mix' field"
            assert isinstance(content_mix['topic_mix'], list), "'topic_mix' should be a list"
            assert 'format_mix' in content_mix, "Content mix is missing 'format_mix' field"
            assert isinstance(content_mix['format_mix'], list), "'format_mix' should be a list"
            
            # Log success message
            print(f"✓ Content strategy validated successfully")
            print(f"✓ Target audience: {strategy.get('target_audience', 'unknown')}")
            print(f"✓ Content purpose: {strategy.get('content_purpose', 'unknown')}")
        
        return True

    # Execute the test
    final_run_status_obj, final_run_outputs = await run_workflow_test(
        test_name=test_name,
        workflow_graph_schema=workflow_graph_schema,
        initial_inputs=test_inputs,
        expected_final_status=WorkflowRunStatus.COMPLETED,
        hitl_inputs=predefined_hitl_inputs,
        setup_docs=setup_docs,
        cleanup_docs_created_by_setup=True,
        cleanup_docs=cleanup_docs,
        validate_output_func=validate_content_strategy_output,
        stream_intermediate_results=True,
        poll_interval_sec=5,
        timeout_sec=600
    )

    print(f"--- {test_name} Finished --- ")
    if final_run_outputs and 'generated_output' in final_run_outputs:
        strategy = final_run_outputs['generated_output']
        print(f"Target Audience: {strategy.get('target_audience', 'unknown')}")
        print(f"Content Purpose: {strategy.get('content_purpose', 'unknown')}")
        print(f"Content Format: {strategy.get('content_format', 'unknown')}")
        print(f"Tone and Style: {strategy.get('tone_and_style', 'unknown')}")
        print(f"Relevant Trends: {', '.join(strategy.get('relevant_trends', []))}")
        print(f"Posting Frequency: {strategy.get('posting_schedule', {}).get('frequency', 'unknown')}")

if __name__ == "__main__":
    try:
        asyncio.run(main_test_idea_to_brief_workflow())
    except KeyboardInterrupt:
        print("\nExecution interrupted.")
    except Exception as e:
        print(f"\nError running test: {e}")

