"""

Flow: 
1. input node -> load_all_context_docs and load_draft_posts
2. [load_all_context_docs, load_draft_posts] -> construct_initial_concepts_prompt (enable_node_fan_in true)
3. construct_initial_concepts_prompt -> generate_concepts
4. generate_concepts -> store_concepts
5. store_concepts -> capture_user_choice
5. capture_user_choice -> route_on_user_choice
6. route_on_user_choice -> construct_concepts_regeneration_prompt [selection: regenerate concepts]
7. route_on_user_choice -> output_node [selection: Go back to initial ideas brief generation]
8. route_on_user_choice -> filter_selected_concepts [selection: select list of concepts]
9. construct_concepts_regeneration_prompt -> generate_concepts (concepts regeneration loop, generate_concepts reads message_history from state)
10. filter_selected_concepts -> construct_update_content_brief_prompt
11. construct_update_content_brief_prompt -> generated_updated_content_brief
12. generated_updated_content_brief -> save_updated_content_brief
13. save_updated_content_brief -> output_node
"""

import asyncio
import logging
from typing import Dict, Any, Optional, List, Union, ClassVar, Type
import json
from enum import Enum

# Using Pydantic for easier schema generation
from pydantic import BaseModel, Field

# Internal dependencies
from kiwi_client.test_run_workflow_client import (
    run_workflow_test,
    SetupDocInfo,
    CleanupDocInfo
)
from kiwi_client.schemas.workflow_constants import WorkflowRunStatus

# --- Workflow Configuration Constants ---
# Namespaces and storage
USER_PROFILES_NAMESPACE = "user_profiles"
USER_DNA_DOCNAME = "user_dna_doc"
USER_PREFERENCES_DOCNAME = "user_preferences_doc"
DRAFT_POSTS_NAMESPACE = "draft_posts"
GENERATED_BRIEFS_NAMESPACE = "generated_briefs"
GENERATED_CONCEPTS_NAMESPACE = "generated_concepts"
STRATEGY_DOCS_NAMESPACE = "strategy_docs"
CONTENT_STRATEGY_DOCNAME = "content_strategy_doc"
GENERATED_BRIEFS_DOCNAME_PATTERN = "content_brief_{item}"
GENERATED_CONCEPTS_DOCNAME_PATTERN = "content_concepts_{item}"

# LLM Configuration
LLM_PROVIDER = "openai"
GENERATION_MODEL = "gpt-4.1"
LLM_TEMPERATURE = 1
LLM_MAX_TOKENS = 4000

# Workflow Defaults
PAST_CONTEXT_POSTS_LIMIT = 20  # Limit for context posts

# --- Pydantic Schemas for LLM Outputs ---
class ContentBriefSchema(BaseModel):
    """
    Defines the structure for a single content brief generated by the LLM.
    """
    brief_id: str = Field(..., description="Unique identifier for this brief (e.g., iteration number or UUID).")
    topic: str = Field(..., description="The core subject or theme for the LinkedIn post.")
    angle_or_hook: str = Field(..., description="A specific angle, perspective, or hook to make the post engaging.")
    key_talking_points: List[str] = Field(..., description="Bulleted list of essential points or messages to include.")
    call_to_action: Optional[str] = Field(None, description="A suggested call to action for the reader.")
    suggested_hashtags: List[str] = Field(default_factory=list, description="Relevant hashtags to potentially include.")

class ConceptSchema(BaseModel):
    """
    Defines the structure for content concepts generated during the ideation phase.
    """
    concept_id: str = Field(..., description="Unique identifier for this concept.")
    title: str = Field(..., description="Short title or name for this concept.")
    description: str = Field(..., description="Brief description of the concept.")
    topic_area: str = Field(..., description="The broad topic area this concept fits into.")
    target_audience: Optional[str] = Field(None, description="The intended audience for this concept.")
    key_points: List[str] = Field(..., description="Key points or ideas to include in this concept.")
    potential_angles: List[str] = Field(default_factory=list, description="Potential angles or perspectives for this concept.")

class ConceptListSchema(BaseModel):
    """
    Defines the structure for a list of content concepts.
    """
    concepts: List[ConceptSchema] = Field(..., description="List of content concepts.")


workflow_graph_schema = {
  "nodes": {
        # --- 1. Input Node ---
        "input_node": {
            "node_id": "input_node",
            "node_name": "input_node",
            "node_config": {},
            "dynamic_output_schema": {
                    "fields": {
                        "customer_context_doc_configs": {
                            "type": "list",
                            "required": True,
                            "description": "List of document identifiers (namespace/docname pairs) for customer context like DNA, strategy docs."
                        },
                        
                        "past_context_posts_limit": { "type": "int", "required": False, "default": PAST_CONTEXT_POSTS_LIMIT, "description": f"Max number of combined posts (drafts + scraped) to use for context (default: {PAST_CONTEXT_POSTS_LIMIT})."},
                        "initial_brief_docname": { "type": "str", "required": True, "description": "Name of the initial brief document."},
                        # "entity_name": {"type": "str", "required": True},
                    }
            }
                # Outputs: user_id, weeks_to_generate, customer_context_doc_configs, past_context_posts_limit -> $graph_state
        },

        # --- 2. Load Customer Context Documents and Scraped Posts (Single Node) ---
        "load_all_context_docs": {
            "node_id": "load_all_context_docs",
            "node_name": "load_customer_data",
            "node_config": {
                # Configure to load multiple documents based on the input list
                "load_configs_input_path": "customer_context_doc_configs", # Use the list from input node
                # Global defaults (can be overridden if needed per doc type via input structure)
                "global_is_shared": False,
                "global_is_system_entity": False,
                # "global_version_config": {"version": "default"},
                "global_schema_options": {"load_schema": False},
            },
        },

        # --- 3. Load Latest User Draft Posts ---
        "load_draft_posts": {
            "node_id": "load_draft_posts",
            "node_name": "load_multiple_customer_data", # Use the multi-loader node
            "node_config": {
                "namespace_filter": DRAFT_POSTS_NAMESPACE, # Filter by draft namespace
                "include_shared": False,        # User-specific drafts only
                "include_user_specific": True,
                "include_system_entities": False,
                # Pagination and Sorting (Inputs mapped from state)
                "skip": 0,
                "limit": PAST_CONTEXT_POSTS_LIMIT, # Mapped from draft_posts_limit input
                "sort_by": "updated_at",
                "sort_order": "desc",

                # Loading options (default)
                "global_version_config": None, # Load active version if versioned
                "global_schema_options": {"load_schema": False},

                # Output field name
                "output_field_name": "draft_posts" # The list will be under this key
            },
        },



        # --- 9. Construct Brief Prompt (Inside Map Branch) ---
        "construct_initial_concepts_prompt": {
            "node_id": "construct_initial_concepts_prompt",
            "node_name": "prompt_constructor",
            "enable_node_fan_in": True,  # Wait for all data loads before proceeding
            "node_config": {
                "prompt_templates": {
                    "initial_concepts_user_prompt": {
                        "id": "initial_concepts_user_prompt",
                        "template": """Generate initial content concepts for LinkedIn posts.

                        **Context:**
                        - Initial Brief: {initial_brief}
                        - User DNA: {user_dna}
                        - Content Strategy: {strategy_doc}
                        - User Preferences: {user_preferences}
                        - Recent User Posts: {draft_posts}

                        **Task:**
                        Generate 3 distinct content concepts that could be developed into LinkedIn posts.
                        Each concept should include a title, description, topic area, and key points.
                        Ensure variety in the concepts to give the user different options.

                        Respond ONLY with the JSON object matching the specified schema.
                        """,
                        "variables": {
                            "initial_brief": None,
                            "user_dna": None,
                            "strategy_doc": None,
                            "user_preferences": None,
                            "draft_posts": None,
                        },
                        "construct_options": {
                            "initial_brief": "initial_brief",
                            "user_dna": "user_dna",
                            "strategy_doc": "strategy_doc",
                            "user_preferences": "user_preferences",
                            "draft_posts": "draft_posts",
                        }
                    },
                    "concepts_system_prompt": {
                        "id": "concepts_system_prompt",
                        "template": "You are an expert LinkedIn content strategist. Generate between 3-4 unique initial content concepts based on the provided user context. Respond strictly with the JSON output conforming to the schema: ```json\n{schema}\n```",
                        "variables": { "schema": json.dumps(ConceptSchema.model_json_schema(), indent=2) },
                        "construct_options": {}
                    }
                }
            }
        },

        # --- 10. Generate Brief (LLM - Inside Map Branch) ---
        "generate_concepts": {
            "node_id": "generate_concepts",
            "node_name": "llm",
            "node_config": {
                "llm_config": {
                    "model_spec": {"provider": LLM_PROVIDER, "model": GENERATION_MODEL},
                    "temperature": LLM_TEMPERATURE,
                    "max_tokens": LLM_MAX_TOKENS
                },
                "output_schema": {
                    "schema_definition": ConceptListSchema.model_json_schema()
                },
            }
        },

        # --- 5. Store Concepts ---
        "store_concepts": {
            "node_id": "store_concepts",
            "node_name": "store_customer_data",
            "node_config": {
                    "global_versioning": {
                    "is_versioned": True,
                    "operation": "upsert_versioned", # Must not exist yet
                    "version": "generated_draft" # Name the initial version
                },
                "store_configs": [
                {
                    "input_field_path": "structured_output", # Field name in node input containing the value to save
                    "target_path": {
                        "filename_config": {
                            "static_namespace": GENERATED_CONCEPTS_NAMESPACE,
                            "input_docname_field": "initial_brief.brief_id", # Field in node's input containing the value
                            "input_docname_field_pattern": GENERATED_CONCEPTS_DOCNAME_PATTERN  # 'item' here will be the value of entity_name
                            }
                    }
                }
                ]
            }
            },

        # --- 6. Human Review ---
        "capture_user_choice": {
            "node_id": "capture_user_choice",
            "node_name": "hitl_node__default",
            "node_config": {}, # Config removed as base HITLNode ignores it
            "dynamic_output_schema": {
                "fields": {
                    "approval_status": { 
                        "type": "enum", 
                        "enum_values": ["regenerate", "restart_from_idea_generation", "select_concepts"],   # TODO: support select only 1 concept for now
                        "required": True, 
                        "description": "User action choice" 
                    },
                    "feedback_text": { 
                        "type": "str", 
                        "required": False, 
                        "description": "Optional feedback for regeneration" 
                    },
                    "selected_concepts": {
                        "type": "list",
                        "items_type": "str",
                        "required": False,
                        "description": "List of concept_ids the user selected if approval_status is 'select_concepts'"
                    }
                }
            }
        },

        # --- 7. Route Based on Approval ---
        "route_on_user_choice": {
            "node_id": "route_on_user_choice",
            "node_name": "router_node",
            "node_config": {
                "choices": ["construct_concepts_regeneration_prompt", "output_node", "filter_selected_concepts"],
                "allow_multiple": False,
                "choices_with_conditions": [
                {
                    "choice_id": "construct_concepts_regeneration_prompt",
                    "input_path": "user_choice_action",
                    "target_value": "regenerate"
                },
                {
                    "choice_id": "output_node",
                    "input_path": "user_choice_action",
                    "target_value": "restart_from_idea_generation"
                },
                {
                    "choice_id": "filter_selected_concepts",
                    "input_path": "user_choice_action",
                    "target_value": "select_concepts"
                }
                ]
            }
        },

        # --- Construct Additional Brief Prompt ---
        "construct_concepts_regeneration_prompt": {
            "node_id": "construct_concepts_regeneration_prompt",
            "node_name": "prompt_constructor",
            "node_config": {
                "prompt_templates": {
                "additional_brief_prompt": {
                    "id": "additional_brief_prompt",
                    "template": "Generate more content concepts. Please consider this feedback: {feedback_text}. Ensure the new concepts are different from previous ones and follow the same schema.",
                    "variables": {
                        "feedback_text": None
                    },
                    "construct_options": {
                        "feedback_text": "current_feedback_text"
                    }
                },
                }
            }
            # Reads: updated_brief from state
            # Writes: additional_brief_prompt, system_prompt
        },


        # --- Filter Selected Concepts ---
        "filter_selected_concepts": {
            "node_id": "filter_selected_concepts",
            "node_name": "filter_data",
            "node_config": {
                "targets": [
                    {
                        "filter_target": "concepts.concepts",  # Target the concepts list
                        "condition_groups": [
                            {
                                "conditions": [
                                    {
                                        "field": "concepts.concepts.concept_id",
                                        "operator": "equals_any_of",
                                        "value_path": "selected_concepts"
                                    }
                                ]
                            }
                        ],
                        "filter_mode": "allow"  # Only allow concepts that match the condition
                    },
                    # {
                    #     # Remove selected concepts from filtered data!
                    #     # NOTE: be careful about deleting 
                    #     "filter_target": "selected_concepts",  # Target the concepts list
                    #     "condition_groups": [
                    #         {
                    #             "conditions": [
                    #                 {
                    #                     "field": "selected_concepts",
                    #                     "operator": "is_not_empty",
                    #                 }
                    #             ]
                    #         }
                    #     ],
                    #     "filter_mode": "deny"  # Only allow concepts that match the condition
                    # }
                ]
            }
        },


        # --- 9. Construct Brief Prompt (Inside Map Branch) ---
        "construct_update_content_brief_prompt": {
            "node_id": "construct_update_content_brief_prompt",
            "node_name": "prompt_constructor",
            "node_config": {
                "prompt_templates": {
                    "brief_user_prompt": {
                        "id": "brief_user_prompt",
                        "template": """Update the content brief based on the selected concepts.

                        **Selected Concepts:**
                        {selected_concepts}

                        **User Context:**
                        - User DNA: {user_dna}
                        - Content Strategy: {strategy_doc}
                        - User Preferences: {user_preferences}

                        **Initial Brief:**
                        - Initial Brief: {initial_brief}

                        **Task:**
                        Develop a comprehensive content brief that expands on the selected concepts.
                        The brief should include a refined topic, compelling angle/hook, detailed key talking points,
                        a clear call to action, and relevant hashtags.

                        Use the details from the selected concepts (title, description, topic area, key points) as
                        the foundation for developing the content brief.

                        Respond ONLY with the JSON object matching the specified schema.
                        """,
                        "variables": {
                            "selected_concepts": None,
                            "user_dna": None,
                            "strategy_doc": None,
                            "user_preferences": None,
                            "initial_brief": None
                        },
                        "construct_options": {
                            "selected_concepts": "selected_concepts.concepts",
                            "user_dna": "user_dna",
                            "strategy_doc": "strategy_doc",
                            "user_preferences": "user_preferences",
                            "initial_brief": "initial_brief"
                        }
                    },
                    "brief_system_prompt": {
                        "id": "brief_system_prompt",
                        "template": "You are an expert LinkedIn content strategist. Update the content brief based on the selected concepts and user context. Ensure you use the same brief ID as the initial brief. Respond strictly with the JSON output conforming to the schema: ```json\n{schema}\n```",
                        "variables": { "schema": json.dumps(ContentBriefSchema.model_json_schema(), indent=2) },
                        "construct_options": {}
                    }
                }
            }
        },

        # --- 10. Generate Brief (LLM - Inside Map Branch) ---
        "generated_updated_content_brief": {
            "node_id": "generated_updated_content_brief",
            "node_name": "llm",
            "node_config": {
                "llm_config": {
                    "model_spec": {"provider": LLM_PROVIDER, "model": GENERATION_MODEL},
                    "temperature": LLM_TEMPERATURE,
                    "max_tokens": LLM_MAX_TOKENS
                },
                "output_schema": {
                    "schema_definition": ContentBriefSchema.model_json_schema()
                },
            }
        },

        # --- 11. Store All Generated Briefs (After Map Completes) ---
        "save_updated_content_brief": {
            "node_id": "save_updated_content_brief",
            "node_name": "store_customer_data", # Store the final list
            "node_config": {
                "global_versioning": { "is_versioned": True, "operation": "upsert_versioned", "version": "final" },
                "global_is_shared": False,
                "store_configs": [
                    {
                        # Store the final content brief
                        "input_field_path": "updated_brief", # Mapped from LLM output
                        "target_path": {
                            "filename_config": {
                                "static_namespace": GENERATED_BRIEFS_NAMESPACE,
                                "input_docname_field": "brief_docname"
                            }
                        },
                    },
                    {
                        # Also store the selected concepts that were used
                        "input_field_path": "selected_concepts.concepts", # Mapped from filter_selected_concepts
                        "target_path": {
                            "filename_config": {
                                "static_namespace": GENERATED_CONCEPTS_NAMESPACE,
                                "input_docname_field": "initial_brief.brief_id", # Field in node's input containing the value
                                "input_docname_field_pattern": GENERATED_CONCEPTS_DOCNAME_PATTERN  # 'item' here will be the value of entity_name
                            }
                        },
                    }
                ],
            }
            # Reads: updated_brief, user_id (from state)
            # Writes: paths_processed
        },


        # --- 12. Output Node ---
        "output_node": {
            "node_id": "output_node",
            "node_name": "output_node",
            "node_config": {},
            # "dynamic_input_schema": { # Define expected final inputs
            #     "fields": {
            #         "final_briefs_list": { "type": "list", "required": True, "description": "The complete list of generated content briefs." },
            #         "brief_paths_processed": { "type": "list", "required": False, "description": "Confirmation/path from the storage operation." }
            #     }
            # }
            # Reads: updated_brief (mapped to final_briefs_list), paths_processed (mapped to save_confirmation)
        },




    },

    # --- Edges Defining Data Flow ---
    "edges": [
        # --- Initial Setup ---
        # Input -> State: Store initial inputs globally
        { "src_node_id": "input_node", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "customer_context_doc_configs", "dst_field": "customer_context_doc_configs" },
            { "src_field": "past_context_posts_limit", "dst_field": "past_context_posts_limit" },
            { "src_field": "initial_brief_docname", "dst_field": "initial_brief_docname" },
          ]
        },
        
        # Input -> Load operations
        { "src_node_id": "input_node", "dst_node_id": "load_all_context_docs", "mappings": [
            { "src_field": "customer_context_doc_configs", "dst_field": "customer_context_doc_configs" },
            { "src_field": "initial_brief_docname", "dst_field": "initial_brief_docname" },
          ], "description": "Trigger context docs loading."
        },

        { "src_node_id": "input_node", "dst_node_id": "load_draft_posts", "description": "Trigger draft posts loading." },

        # --- State Updates from Loaders ---
        { "src_node_id": "load_all_context_docs", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "user_dna", "dst_field": "user_dna"},
            { "src_field": "user_preferences", "dst_field": "user_preferences"},
            { "src_field": "strategy_doc", "dst_field": "strategy_doc"},
            { "src_field": "initial_brief", "dst_field": "initial_brief"}
          ]
        },

        { "src_node_id": "load_draft_posts", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "draft_posts", "dst_field": "draft_posts"}
          ]
        },

        # --- Trigger Initial Concept Generation ---
        { "src_node_id": "load_all_context_docs", "dst_node_id": "construct_initial_concepts_prompt" },
        { "src_node_id": "load_draft_posts", "dst_node_id": "construct_initial_concepts_prompt" },

        # --- Mapping State to Initial Concepts Prompt ---
        { "src_node_id": "$graph_state", "dst_node_id": "construct_initial_concepts_prompt", "mappings": [
            { "src_field": "draft_posts", "dst_field": "draft_posts" },
            { "src_field": "user_preferences", "dst_field": "user_preferences"},
            { "src_field": "strategy_doc", "dst_field": "strategy_doc" },
            { "src_field": "user_dna", "dst_field": "user_dna" },
            { "src_field": "initial_brief", "dst_field": "initial_brief" },
          ]
        },

        # --- Construct Prompt → Generate Concepts ---
        { "src_node_id": "construct_initial_concepts_prompt", "dst_node_id": "generate_concepts", "mappings": [
            { "src_field": "initial_concepts_user_prompt", "dst_field": "user_prompt"},
            { "src_field": "concepts_system_prompt", "dst_field": "system_prompt"}
          ], "description": "Send prompts to LLM for concept generation."
        },

        # --- State -> Generate Concepts ---
        { "src_node_id": "$graph_state", "dst_node_id": "generate_concepts", "mappings": [
            { "src_field": "messages_history", "dst_field": "messages_history"}
          ]
        },

        # --- Generate Concepts -> Store & State ---
        { "src_node_id": "generate_concepts", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "structured_output", "dst_field": "current_generated_concepts"},
            { "src_field": "current_messages", "dst_field": "messages_history"}
          ]
        },

        { "src_node_id": "generate_concepts", "dst_node_id": "store_concepts", "mappings": [
            { "src_field": "structured_output", "dst_field": "structured_output"}
          ]
        },

        # --- State -> Store Concepts ---
        { "src_node_id": "$graph_state", "dst_node_id": "store_concepts", "mappings": [
            { "src_field": "initial_brief", "dst_field": "initial_brief"}
          ]
        },

        # --- Store Concepts -> User Choice ---
        { "src_node_id": "store_concepts", "dst_node_id": "capture_user_choice", "mappings": [
            { "src_field": "paths_processed", "dst_field": "draft_paths_processed"}
          ]
        },

        # --- State -> User Choice ---
        { "src_node_id": "$graph_state", "dst_node_id": "capture_user_choice", "mappings": [
            { "src_field": "current_generated_concepts", "dst_field": "concepts_for_review"}
          ]
        },

        # --- User Choice -> Route ---
        { "src_node_id": "capture_user_choice", "dst_node_id": "route_on_user_choice", "mappings": [
            { "src_field": "approval_status", "dst_field": "user_choice_action"},
          ]
        },

        # --- User Choice -> State ---
        { "src_node_id": "capture_user_choice", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "feedback_text", "dst_field": "current_feedback_text"},
            { "src_field": "selected_concepts", "dst_field": "user_selected_concepts"}
          ]
        },

        # --- Route -> Paths ---
        { "src_node_id": "route_on_user_choice", "dst_node_id": "construct_concepts_regeneration_prompt", "description": "Route to regenerate concepts if requested." },
        { "src_node_id": "route_on_user_choice", "dst_node_id": "output_node", "description": "Route to output if going back." },
        { "src_node_id": "route_on_user_choice", "dst_node_id": "filter_selected_concepts", "description": "Route to filter if concepts selected." },

        # --- Regeneration Prompt -> Generate Concepts ---
        { "src_node_id": "$graph_state", "dst_node_id": "construct_concepts_regeneration_prompt", "mappings": [
            { "src_field": "current_feedback_text", "dst_field": "current_feedback_text"}
          ]},

        { "src_node_id": "construct_concepts_regeneration_prompt", "dst_node_id": "generate_concepts", "mappings": [
            { "src_field": "additional_brief_prompt", "dst_field": "user_prompt"}
          ]
        },

        # --- State -> Filter ---
        { "src_node_id": "$graph_state", "dst_node_id": "filter_selected_concepts", "mappings": [
            { "src_field": "current_generated_concepts", "dst_field": "concepts"},
            { "src_field": "user_selected_concepts", "dst_field": "selected_concepts"}
          ]
        },

        # --- Filter -> Update Content Brief Prompt ---
        { "src_node_id": "filter_selected_concepts", "dst_node_id": "construct_update_content_brief_prompt", "mappings": [
            { "src_field": "filtered_data", "dst_field": "selected_concepts"}
          ]
        },

        # --- Filter -> Save Updated Content Brief (to also save selected concepts) ---
        # NOTE: overwrites user choices with filtered concepts!
        { "src_node_id": "filter_selected_concepts", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "filtered_data", "dst_field": "selected_concepts"}
          ]
        },

        # --- State -> Update Content Brief Prompt ---
        { "src_node_id": "$graph_state", "dst_node_id": "construct_update_content_brief_prompt", "mappings": [
            { "src_field": "user_dna", "dst_field": "user_dna" },
            { "src_field": "user_preferences", "dst_field": "user_preferences" },
            { "src_field": "strategy_doc", "dst_field": "strategy_doc" },
            { "src_field": "initial_brief", "dst_field": "initial_brief"}
          ]
        },

        # --- Update Content Brief Prompt -> Generate Updated Brief ---
        { "src_node_id": "construct_update_content_brief_prompt", "dst_node_id": "generated_updated_content_brief", "mappings": [
            { "src_field": "brief_user_prompt", "dst_field": "user_prompt"},
            { "src_field": "brief_system_prompt", "dst_field": "system_prompt"}
          ]
        },

        # --- Generate Updated Brief -> State ---
        { "src_node_id": "generated_updated_content_brief", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "structured_output", "dst_field": "updated_brief"},
            # { "src_field": "current_messages", "dst_field": "brief_messages_history"}
          ]
        },

        # --- Generate Updated Brief -> Save ---
        { "src_node_id": "generated_updated_content_brief", "dst_node_id": "save_updated_content_brief", "mappings": [
            { "src_field": "structured_output", "dst_field": "updated_brief"}
          ]
        },

        # --- State -> Save ---
        { "src_node_id": "$graph_state", "dst_node_id": "save_updated_content_brief", "mappings": [
            { "src_field": "initial_brief_docname", "dst_field": "brief_docname"},
            { "src_field": "initial_brief", "dst_field": "initial_brief"},
            { "src_field": "selected_concepts", "dst_field": "selected_concepts"}
        ]},

        # --- Save -> Output ---
        { "src_node_id": "save_updated_content_brief", "dst_node_id": "output_node", "mappings": [
            { "src_field": "paths_processed", "dst_field": "brief_paths_processed"}
          ]
        },

        # --- State -> Output ---
        { "src_node_id": "$graph_state", "dst_node_id": "output_node", "mappings": [
            { "src_field": "updated_brief", "dst_field": "final_brief_content"},
            { "src_field": "selected_concepts", "dst_field": "selected_concepts"},
          ]
        },
    ],

    # --- Define Start and End ---
    "input_node_id": "input_node",
    "output_node_id": "output_node",

    # --- State Reducers ---
    "metadata": {
        "$graph_state": {
            "reducer": {
                # NOTE: If you set collect_values reducer here, it distorts / nests the concepts structure and fails the FILTER NODE!
                # "current_generated_concepts": "collect_values",
                # "messages_history": "add_messages"
            }
        }
    }
}

# --- Test Execution Logic ---
async def main_test_idea_to_brief_workflow():
    """
    Test for Idea to Brief Workflow.
    """
    test_name = "Idea to Brief Workflow Test"
    print(f"--- Starting {test_name} --- ")

    # Example Inputs
    test_context_docs = [
        {
            "filename_config": {
                "static_namespace": USER_PROFILES_NAMESPACE, 
                "static_docname": USER_DNA_DOCNAME,
            },
            "output_field_name": "user_dna"
        },
        {
            "filename_config": {
                "static_namespace": USER_PROFILES_NAMESPACE, 
                "static_docname": USER_PREFERENCES_DOCNAME,
            },
            "output_field_name": "user_preferences"
        },
        {
            "filename_config": {
                "static_namespace": STRATEGY_DOCS_NAMESPACE, 
                "static_docname": CONTENT_STRATEGY_DOCNAME,
            },
            "output_field_name": "strategy_doc"
        },
        {
            "filename_config": {
                "static_namespace": GENERATED_BRIEFS_NAMESPACE,
                "input_docname_field": "initial_brief_docname"
            },
            "output_field_name": "initial_brief"
        }
    ]
    
    brief_docname = "test_brief_1"
    
    test_inputs = {
        "initial_brief_docname": brief_docname,
        "customer_context_doc_configs": test_context_docs,
        "past_context_posts_limit": 20
    }

    # Define setup documents
    setup_docs = [
        {
            'namespace': USER_PROFILES_NAMESPACE, 
            'docname': USER_DNA_DOCNAME,
            'initial_data': {
                "professional_background": "Marketing executive",
                "expertise_areas": ["Digital Marketing", "Brand Strategy"],
                "target_audience": "Marketing professionals",
                "personal_style": "Conversational but authoritative"
            }, 
            'is_versioned': False, 
            'is_shared': False
        },
        {
            'namespace': USER_PROFILES_NAMESPACE, 
            'docname': USER_PREFERENCES_DOCNAME,
            'initial_data': {
                "posts_per_week": 2,
                "preferred_posting_days": ["Monday", "Thursday"],
                "preferred_topics": ["Leadership", "Marketing Trends"],
                "content_tone": "Professional"
            }, 
            'is_versioned': False, 
            'is_shared': False
        },
        {
            'namespace': STRATEGY_DOCS_NAMESPACE, 
            'docname': CONTENT_STRATEGY_DOCNAME,
            'initial_data': {
                "quarterly_focus": "Building personal brand",
                "key_themes": ["Innovation", "Leadership", "Industry disruption"],
                "content_pillars": ["Educational", "Inspirational"]
            }, 
            'is_versioned': False, 
            'is_shared': False
        },
        {
            'namespace': GENERATED_BRIEFS_NAMESPACE, 
            'docname': brief_docname,
            'initial_data': {
                "brief_id": brief_docname,
                "topic": "Building personal brand in the digital marketing landscape",
                "angle_or_hook": "How innovative leadership approaches can disrupt traditional marketing paradigms",
                "key_talking_points": [
                    "The intersection of personal branding and digital marketing strategy",
                    "Leadership principles that foster innovation in marketing teams",
                    "Case studies of industry disruption through personal brand leverage",
                    "Metrics that matter when measuring personal brand impact"
                ],
                "target_audience": "Marketing professionals looking to differentiate themselves",
                "content_purpose": "Educational and inspirational guidance for marketing leaders",
                "call_to_action": "Connect with me to discuss how we can revolutionize your marketing approach",
                "suggested_hashtags": ["#PersonalBrand", "#MarketingInnovation", "#LeadershipStrategy", "#IndustryDisruption", "#DigitalMarketing"],
                "content_format": "LinkedIn article with supporting visuals",
                "tone_and_style": "Professional with authoritative insights, conversational yet data-backed",
                "relevant_trends": ["Rise of personal brand as business currency", "Shift from traditional to digital-first marketing strategies"],
                "key_statistics": ["78% of marketing executives believe personal branding directly impacts business outcomes", "Companies with strong leadership brands see 31% higher customer retention"],
                "posting_schedule": {
                    "preferred_day": "Monday",
                    "preferred_time": "9:00 AM",
                    "time_zone": "EST"
                }
            }, 
            'initial_version': "draft",
            'is_versioned': True, 
            'is_shared': False
        },

        # Mock draft posts
        {
            'namespace': DRAFT_POSTS_NAMESPACE, 
            'docname': f"draft_post_1",
            'initial_data': {
                "title": "Thoughts on AI in Marketing *****",
                "content": "AI is transforming how we approach marketing campaigns...",
                "created_at": "2023-06-01T10:00:00Z",
                "updated_at": "2023-06-02T14:30:00Z",
                "status": "draft"
            }, 
            'is_versioned': False, 
            'is_shared': False
        },
        {
            'namespace': DRAFT_POSTS_NAMESPACE, 
            'docname': f"draft_post_2",
            'initial_data': {
                "title": "Leadership Lessons from 2023 *****",
                "content": "This year has taught me valuable lessons about remote leadership...",
                "created_at": "2023-06-05T09:15:00Z",
                "updated_at": "2023-06-05T16:45:00Z",
                "status": "draft"
            }, 
            'is_versioned': False, 
            'is_shared': False
        },
    ]

    # Define cleanup docs
    cleanup_docs = [
        {'namespace': USER_PROFILES_NAMESPACE, 'docname': USER_DNA_DOCNAME, 'is_versioned': False, 'is_shared': False},
        {'namespace': USER_PROFILES_NAMESPACE, 'docname': USER_PREFERENCES_DOCNAME, 'is_versioned': False, 'is_shared': False},
        {'namespace': STRATEGY_DOCS_NAMESPACE, 'docname': CONTENT_STRATEGY_DOCNAME, 'is_versioned': False, 'is_shared': False},
        {'namespace': GENERATED_BRIEFS_NAMESPACE, 'docname': brief_docname, 'is_versioned': True, 'is_shared': False},
        {'namespace': GENERATED_CONCEPTS_NAMESPACE, 'docname': "content_concepts_" + brief_docname, 'is_versioned': True, 'is_shared': False},
        {'namespace': DRAFT_POSTS_NAMESPACE, 'docname': "draft_post_1", 'is_versioned': False, 'is_shared': False},
        {'namespace': DRAFT_POSTS_NAMESPACE, 'docname': "draft_post_2", 'is_versioned': False, 'is_shared': False},
    ]

    # Predefined HITL inputs
    predefined_hitl_inputs = [
        # {
        #     "approval_status": "select_concepts",  # "regenerate", "restart_from_idea_generation"
        #     "selected_concepts": ["concept_1", "concept_2"],
        # }
        # feedback_text  ;  
    ]
    # VALID HUMAN INPUTS TYPE TO CONSOLE DIRECTLY, ENSURE SELECTED ID IS EXACT MATCH TO GENERATED!
    # {"approval_status": "select_concepts", "selected_concepts": ["concept_004"]}
    # {"approval_status": "regenerate"}
    # {"approval_status": "restart_from_idea_generation"}

    # Output validation function
    async def validate_brief_output(outputs):
        assert outputs is not None, "Validation Failed: Workflow returned no outputs."
        assert 'final_brief_content' in outputs, "Validation Failed: 'final_brief_content' missing."
        assert 'brief_paths_processed' in outputs, "Validation Failed: 'brief_paths_processed' missing."
        
        # Validate the content structure
        if 'final_brief_content' in outputs:
            brief = outputs['final_brief_content']
            assert 'brief_id' in brief, "Brief is missing 'brief_id' field"
            assert 'topic' in brief, "Brief is missing 'topic' field"
            assert 'key_talking_points' in brief, "Brief is missing 'key_talking_points' field"
            # Log success message
            print(f"✓ Final brief validated successfully with topic: {brief.get('topic', 'unknown')}")
        
        return True

    # Execute the test
    final_run_status_obj, final_run_outputs = await run_workflow_test(
        test_name=test_name,
        workflow_graph_schema=workflow_graph_schema,
        initial_inputs=test_inputs,
        expected_final_status=WorkflowRunStatus.COMPLETED,
        hitl_inputs=predefined_hitl_inputs,
        setup_docs=setup_docs,
        cleanup_docs=cleanup_docs,
        validate_output_func=validate_brief_output,
        stream_intermediate_results=True,
        poll_interval_sec=5,
        timeout_sec=600
    )

    print(f"--- {test_name} Finished --- ")
    if final_run_outputs and 'final_brief_content' in final_run_outputs:
        brief = final_run_outputs['final_brief_content']
        print(f"Generated Brief Topic: {brief.get('topic')}")
        print(f"Generated Brief Call to Action: {brief.get('call_to_action')}")
        print(f"Generated Brief Hashtags: {brief.get('suggested_hashtags')}")

if __name__ == "__main__":
    try:
        asyncio.run(main_test_idea_to_brief_workflow())
    except KeyboardInterrupt:
        print("\nExecution interrupted.")
    except Exception as e:
        print(f"\nError running test: {e}")

