#!/bin/bash
# Revised entrypoint.sh for Nginx + Certbot container
# Exit immediately if a command exits with a non-zero status.
set -e

# --- Environment Variable Checks ---
# Ensure required environment variables are set. Fail script if not.
: "${YOUR_DOMAIN:?Error: YOUR_DOMAIN environment variable is not set.}"
: "${APP_HOST:?Error: APP_HOST environment variable is not set.}"
: "${APP_PORT:?Error: APP_PORT environment variable is not set.}"
: "${CERTBOT_EMAIL:?Error: CERTBOT_EMAIL environment variable is not set.}"
echo "Environment variables checked."

# --- Create Dummy SSL Files & Dirs if They Don't Exist ---
# This allows Nginx's config check (-t) and initial startup to pass
# even before Certbot has obtained real certificates.
# Assumes running as root or user with permissions for /etc/letsencrypt

SSL_BASE_DIR="/etc/letsencrypt"
SSL_LIVE_DIR="${SSL_BASE_DIR}/live/${YOUR_DOMAIN}"
OPTIONS_SSL_CONF="${SSL_BASE_DIR}/options-ssl-nginx.conf"
SSL_DHPARAMS="${SSL_BASE_DIR}/ssl-dhparams.pem"

# Ensure base directory exists
mkdir -p "${SSL_BASE_DIR}"

# Create placeholder options-ssl-nginx.conf if it doesn't exist
if [ ! -f "${OPTIONS_SSL_CONF}" ]; then
  echo "Creating placeholder ${OPTIONS_SSL_CONF}..."
  # Using recommended options from certbot/certbot defaults
  echo "# Generated by entrypoint.sh for initial Nginx start" > "${OPTIONS_SSL_CONF}"
  echo "ssl_session_cache shared:le_nginx_SSL:10m;" >> "${OPTIONS_SSL_CONF}"
  echo "ssl_session_timeout 1440m;" >> "${OPTIONS_SSL_CONF}"
  echo "ssl_session_tickets off;" >> "${OPTIONS_SSL_CONF}"
  echo "" >> "${OPTIONS_SSL_CONF}"
  echo "ssl_protocols TLSv1.2 TLSv1.3;" >> "${OPTIONS_SSL_CONF}"
  echo "ssl_prefer_server_ciphers off;" >> "${OPTIONS_SSL_CONF}"
  echo "" >> "${OPTIONS_SSL_CONF}"
  echo "ssl_ciphers \"ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384\";" >> "${OPTIONS_SSL_CONF}"
fi

# Create placeholder ssl-dhparams.pem if it doesn't exist
if [ ! -f "${SSL_DHPARAMS}" ]; then
   echo "Creating placeholder ${SSL_DHPARAMS}..."
   # Using simple placeholder text is fastest for startup.
   # Certbot should generate a proper one during issuance if needed/possible.
   echo "# Placeholder ssl-dhparams.pem generated by entrypoint.sh" > "${SSL_DHPARAMS}"
   # If you absolutely need valid DH params for Nginx to start, uncomment openssl command,
   # but be aware it can significantly slow down the first container start.
   # echo "Generating weak DH params (can be slow)..."
   # openssl dhparam -out "${SSL_DHPARAMS}" 2048 &> /dev/null || true
fi

# Create placeholder certificate directory and dummy certs if they don't exist
if [ ! -d "${SSL_LIVE_DIR}" ]; then
   echo "Creating placeholder certificate directory ${SSL_LIVE_DIR} and dummy certs..."
   mkdir -p "${SSL_LIVE_DIR}"
   openssl req -x509 -nodes -newkey rsa:2048 -days 1 \
     -keyout "${SSL_LIVE_DIR}/privkey.pem" \
     -out "${SSL_LIVE_DIR}/fullchain.pem" \
     -subj "/CN=localhost" &> /dev/null
fi
echo "Placeholder SSL files checked/created."

# --- Nginx Configuration Substitution ---
echo "Substituting environment variables in Nginx config template..."
envsubst '${YOUR_DOMAIN} ${APP_HOST} ${APP_PORT}' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf

echo "Nginx configuration generated:"
cat /etc/nginx/conf.d/default.conf # Output the generated config for verification/debugging

# --- Validate Nginx configuration before proceeding ---
echo "Validating generated Nginx configuration..."
nginx -t
if [ $? -ne 0 ]; then
  echo "Nginx configuration validation failed. Exiting."
  exit 1
fi
echo "Nginx configuration is valid."

# --- Start Cron Service ---
echo "Starting Cron daemon..."
# Just starting the service is often enough, -f & is also okay.
cron
echo "Cron daemon started."

# --- Certbot Certificate Management ---
# Define the path again (or reuse variable)
CERT_PATH="/etc/letsencrypt/live/${YOUR_DOMAIN}/fullchain.pem"

# Check if a *real* certificate needs to be obtained (e.g., check expiry or if it's the dummy cert)
# Simple check: if the dummy cert created above still exists, try to get a real one.
# More robust check would involve 'certbot certificates' or openssl x509 expiry checks.
NEEDS_CERT_ISSUANCE=0
if openssl x509 -in "${CERT_PATH}" -subject -noout | grep -q "CN=localhost"; then
  echo "Detected placeholder certificate. Attempting to obtain real one..."
  NEEDS_CERT_ISSUANCE=1
elif ! openssl x509 -checkend 86400 -noout -in "${CERT_PATH}"; then
  # Optional: Check if cert expires within 24 hours (86400 sec) - triggers renewal attempt now
  echo "Certificate expiring soon or already expired. Attempting renewal/issuance..."
  NEEDS_CERT_ISSUANCE=1
fi


if [ "${NEEDS_CERT_ISSUANCE}" -eq 1 ]; then
  echo "Attempting to obtain/renew certificate for ${YOUR_DOMAIN}..."

  # Stop Nginx temporarily (needed for --nginx plugin to bind/modify config)
  echo "Stopping Nginx temporarily..."
  nginx -s stop || echo "Nginx already stopped or failed to stop." # Use || echo instead of || true for clarity

  echo "Running Certbot..."
  certbot certonly --nginx \
    -d "${YOUR_DOMAIN}" \
    --email "${CERTBOT_EMAIL}" \
    --agree-tos \
    --non-interactive \
    --keep-until-expiring \
    --rsa-key-size 4096 \
    --verbose

  # Check the exit status of Certbot.
  CERTBOT_STATUS=$?
  if [ $CERTBOT_STATUS -ne 0 ]; then
    echo "Certbot failed (exit status ${CERTBOT_STATUS}). Check logs for details."
    echo "--- Last 50 lines of Certbot log --- "
    tail -n 50 /var/log/letsencrypt/letsencrypt.log || echo "Could not tail Certbot log file."
    echo "------------------------------------ "
    # Decide if you want to exit or continue with dummy certs/potentially broken https
    echo "WARNING: Failed to obtain real certificate. Nginx will start, but HTTPS might use placeholder certs or fail."
    # exit 1 # Uncomment this to exit immediately on cert failure
  else
    echo "Certificate obtained/renewed successfully."
    # Certbot with --nginx plugin usually reloads Nginx, but we start it below anyway
  fi

  echo "Restarting Nginx after Certbot run attempt..."
  # Nginx will be started by the main CMD via exec "$@" below

elif [ ! -f "${CERT_PATH}" ]; then
    # This case should ideally not be reached if placeholders are created, but as a fallback:
    echo "ERROR: Certificate path ${CERT_PATH} not found and placeholder check failed. Cannot start Nginx securely."
    exit 1
else
  echo "Certificate found and appears valid. Skipping issuance/renewal check."
fi

# --- Start Nginx ---
# The final step is to execute the command passed to this entrypoint script.
# This starts Nginx in the foreground with the now validated configuration
# (either using placeholder certs or real certs obtained by Certbot).
echo "Executing command: $@"
exec "$@"

# The `exec` command replaces the current shell process with the specified command.
