#!/bin/bash
# Revised entrypoint.sh for Nginx + Certbot container
# Exit immediately if a command exits with a non-zero status.
set -e

# --- Environment Variable Checks ---
# Ensure required environment variables are set. Fail script if not.
: "${YOUR_DOMAIN:?Error: YOUR_DOMAIN environment variable is not set.}"
: "${APP_HOST:?Error: APP_HOST environment variable is not set.}"
: "${APP_PORT:?Error: APP_PORT environment variable is not set.}"
: "${CERTBOT_EMAIL:?Error: CERTBOT_EMAIL environment variable is not set.}"
echo "Environment variables checked."

# --- Define SSL File Paths ---
SSL_BASE_DIR="/etc/letsencrypt"
SSL_LIVE_DIR="${SSL_BASE_DIR}/live/${YOUR_DOMAIN}"
OPTIONS_SSL_CONF="${SSL_BASE_DIR}/options-ssl-nginx.conf"
SSL_DHPARAMS="${SSL_BASE_DIR}/ssl-dhparams.pem"
CERT_PRIVKEY="${SSL_LIVE_DIR}/privkey.pem"
CERT_FULLCHAIN="${SSL_LIVE_DIR}/fullchain.pem"

# Ensure base directories exist
mkdir -p "${SSL_BASE_DIR}"
mkdir -p "${SSL_LIVE_DIR}" # Also ensure live dir exists for dummy certs

# --- Create Placeholder/Initial SSL Files if Needed ---

# Create placeholder options-ssl-nginx.conf if it doesn't exist
if [ ! -f "${OPTIONS_SSL_CONF}" ]; then
  echo "Creating placeholder ${OPTIONS_SSL_CONF}..."
  # Using recommended options from certbot/certbot defaults
  echo "# Generated by entrypoint.sh for initial Nginx start" > "${OPTIONS_SSL_CONF}"
  echo "ssl_session_cache shared:le_nginx_SSL:10m;" >> "${OPTIONS_SSL_CONF}"
  echo "ssl_session_timeout 1440m;" >> "${OPTIONS_SSL_CONF}"
  echo "ssl_session_tickets off;" >> "${OPTIONS_SSL_CONF}"
  echo "" >> "${OPTIONS_SSL_CONF}"
  echo "ssl_protocols TLSv1.2 TLSv1.3;" >> "${OPTIONS_SSL_CONF}"
  echo "ssl_prefer_server_ciphers off;" >> "${OPTIONS_SSL_CONF}"
  echo "" >> "${OPTIONS_SSL_CONF}"
  echo "ssl_ciphers \"ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384\";" >> "${OPTIONS_SSL_CONF}"
fi

# CRITICAL FIX: Generate REAL ssl-dhparams.pem if it doesn't exist or is invalid
# This is needed for Nginx to pass validation (`nginx -t`) and start initially.
if [ ! -f "${SSL_DHPARAMS}" ] || ! openssl dhparam -check -in "${SSL_DHPARAMS}" -noout > /dev/null 2>&1; then
   echo "Generating ${SSL_DHPARAMS} (2048 bits). This may take a moment..."
   # Generate real DH parameters. Redirect stdout to /dev/null but keep stderr
   openssl dhparam -out "${SSL_DHPARAMS}" 2048 > /dev/null
   if [ $? -ne 0 ]; then
     echo "ERROR: Failed to generate DH parameters!"
     # Optionally copy a pre-generated weak one as fallback, or exit
     # echo "WARNING: Using fallback DH parameters (less secure)."
     # cp /path/to/fallback/dhparams.pem "${SSL_DHPARAMS}"
     exit 1 # Exit if generation fails and no fallback
   fi
   echo "DH parameters generated."
else
   echo "DH parameters file ${SSL_DHPARAMS} already exists and appears valid."
fi

# Create placeholder/dummy certificate files if they don't exist
if [ ! -f "${CERT_PRIVKEY}" ] || [ ! -f "${CERT_FULLCHAIN}" ]; then
   echo "Creating dummy certificate files in ${SSL_LIVE_DIR}..."
   # Use -addext for Subject Alternative Name (SAN) to avoid some browser warnings with dummy certs
   openssl req -x509 -nodes -newkey rsa:2048 -days 1 \
     -keyout "${CERT_PRIVKEY}" \
     -out "${CERT_FULLCHAIN}" \
     -subj "/CN=localhost" \
     -addext "subjectAltName=DNS:localhost" &> /dev/null
fi
echo "Placeholder/Initial SSL files checked/created."

# --- Nginx Configuration Substitution ---
echo "Substituting environment variables in Nginx config template..."
envsubst '${YOUR_DOMAIN} ${APP_HOST} ${APP_PORT}' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf

echo "Nginx configuration generated:"
cat /etc/nginx/conf.d/default.conf # Output the generated config for verification/debugging

# --- Validate Nginx configuration *AFTER* potentially creating ALL necessary files ---
echo "Validating generated Nginx configuration..."
nginx -t
if [ $? -ne 0 ]; then
  echo "Nginx configuration validation failed. Exiting."
  # Consider outputting Nginx error logs here if possible
  exit 1
fi
echo "Nginx configuration is valid."

# --- Start Cron Service ---
echo "Starting Cron daemon..."
cron # Use `cron -f` if you need it to stay in the foreground for some reason, but usually not needed here.
echo "Cron daemon started."

# --- Certbot Certificate Management ---
# Define the path again (or reuse variable)
# CERT_PATH variable already defined as CERT_FULLCHAIN

# Check if a *real* certificate needs to be obtained
NEEDS_CERT_ISSUANCE=0
# Check if it's the dummy cert by checking the Subject CN
if openssl x509 -in "${CERT_FULLCHAIN}" -subject -noout | grep -q "CN=localhost"; then
  echo "Detected placeholder certificate. Attempting to obtain real one..."
  NEEDS_CERT_ISSUANCE=1
# Optional: Check if cert expires within a certain period (e.g., 1 day = 86400 sec)
# elif ! openssl x509 -checkend 86400 -noout -in "${CERT_FULLCHAIN}"; then
#   echo "Certificate expiring soon or already expired. Attempting renewal/issuance..."
#   NEEDS_CERT_ISSUANCE=1
fi


if [ "${NEEDS_CERT_ISSUANCE}" -eq 1 ]; then
  echo "Attempting to obtain/renew certificate for ${YOUR_DOMAIN}..."

  # Temporarily start Nginx in the background JUST for Certbot challenge validation
  # This avoids stopping/starting if Nginx is already running later
  echo "Temporarily starting Nginx for Certbot challenge..."
  nginx -g 'daemon on;'
  sleep 5 # Give Nginx a moment to start

  echo "Running Certbot..."
  certbot certonly --nginx \
    -d "${YOUR_DOMAIN}" \
    --email "${CERTBOT_EMAIL}" \
    --agree-tos \
    --non-interactive \
    --keep-until-expiring \
    --rsa-key-size 4096 \
    --deploy-hook "nginx -s reload" \ # Add reload hook here too
    --verbose

  # Check the exit status of Certbot.
  CERTBOT_STATUS=$?

  # Stop the temporary Nginx instance regardless of Certbot outcome
  echo "Stopping temporary Nginx..."
  nginx -s stop || echo "Temporary Nginx already stopped or failed to stop."

  if [ $CERTBOT_STATUS -ne 0 ]; then
    echo "Certbot failed (exit status ${CERTBOT_STATUS}). Check logs for details."
    echo "--- Last 50 lines of Certbot log --- "
    tail -n 50 /var/log/letsencrypt/letsencrypt.log || echo "Could not tail Certbot log file."
    echo "------------------------------------ "
    echo "WARNING: Failed to obtain real certificate. Nginx will start using placeholder/dummy certs."
    # exit 1 # Uncomment this to exit immediately on cert failure
  else
    echo "Certificate obtained/renewed successfully. Certbot's deploy hook should have reloaded Nginx if it was running."
  fi

elif [ ! -f "${CERT_FULLCHAIN}" ]; then
    # This case should ideally not be reached if placeholders are created, but as a fallback:
    echo "ERROR: Certificate path ${CERT_FULLCHAIN} not found and placeholder check failed. Cannot start Nginx securely."
    exit 1
else
  echo "Certificate found and appears valid. Skipping initial issuance/renewal check."
fi

# --- Start Nginx (Main Process) ---
# The final step is to execute the command passed to this entrypoint script (CMD).
# This starts Nginx in the foreground with the validated configuration.
echo "Executing command: $@"
exec "$@"
