import asyncio
import logging
from typing import Dict, Any, Optional, List, Union, ClassVar, Type
import json
from enum import Enum

# Using Pydantic for easier schema generation
from pydantic import BaseModel, Field

# Internal dependencies
from kiwi_client.test_run_workflow_client import (
    run_workflow_test,
    SetupDocInfo,
    CleanupDocInfo
)
from kiwi_client.schemas.workflow_constants import WorkflowRunStatus

from kiwi_client.workflows.document_models.customer_docs import (
    # User DNA
    USER_DNA_DOCNAME,
    USER_DNA_NAMESPACE_TEMPLATE,
    USER_DNA_IS_VERSIONED,
    # LinkedIn scraping
    LINKEDIN_SCRAPING_NAMESPACE_TEMPLATE,
    LINKEDIN_POST_DOCNAME,
    # Content Drafts
    CONTENT_DRAFT_DOCNAME,
    CONTENT_DRAFT_NAMESPACE_TEMPLATE,
    CONTENT_DRAFT_IS_VERSIONED,
    # Content Brief
    CONTENT_BRIEF_DOCNAME,
    CONTENT_BRIEF_NAMESPACE_TEMPLATE,
    CONTENT_BRIEF_IS_VERSIONED,
    CONTENT_BRIEF_DEFAULT_VERSION,
    CONTENT_BRIEF_FINAL_VERSION,
    # Content Concept
    CONCEPT_DOCNAME,
    CONCEPT_NAMESPACE_TEMPLATE,
    CONCEPT_IS_VERSIONED
)

from kiwi_client.workflows.llm_inputs.concept_brainstorm_from_scratch import (
    INITIAL_CONCEPTS_USER_PROMPT,
    INITIAL_CONCEPTS_SYSTEM_PROMPT,
    CONCEPTS_SCHEMA,
    ADDITIONAL_CONCEPTS_USER_PROMPT,
    BRIEF_USER_PROMPT_TEMPLATE,
    BRIEF_SYSTEM_PROMPT_TEMPLATE,
    USER_INPUT_INTERPRETATION_SYSTEM_PROMPT,
    USER_INPUT_INTERPRETATION_USER_PROMPT,
    USER_INPUT_INTERPRETATION_SCHEMA,
    BRIEF_LLM_OUTPUT_SCHEMA
)



# LLM Configuration
LLM_PROVIDER = "openai"
GENERATION_MODEL = "gpt-4.1"
LLM_TEMPERATURE = 0.8
LLM_MAX_TOKENS = 4000

# Workflow Defaults
PAST_CONTEXT_POSTS_LIMIT = 10  # Limit for context posts

# # --- Pydantic Schemas for LLM Outputs ---
# class ContentBriefSchema(BaseModel):
#     """
#     Defines the structure for a single content brief generated by the LLM.
#     """
#     brief_id: str = Field(..., description="Unique identifier for this brief (e.g., iteration number or UUID).")
#     topic: str = Field(..., description="The core subject or theme for the LinkedIn post.")
#     angle_or_hook: str = Field(..., description="A specific angle, perspective, or hook to make the post engaging.")
#     key_talking_points: List[str] = Field(..., description="Bulleted list of essential points or messages to include.")
#     call_to_action: Optional[str] = Field(None, description="A suggested call to action for the reader.")
#     suggested_hashtags: List[str] = Field(default_factory=list, description="Relevant hashtags to potentially include.")

# class ConceptSchema(BaseModel):
#     """
#     Defines the structure for content concepts generated during the ideation phase.
#     """
#     concept_id: str = Field(..., description="Unique identifier for this concept.")
#     title: str = Field(..., description="Short title or name for this concept.")
#     description: str = Field(..., description="Brief description of the concept.")
#     topic_area: str = Field(..., description="The broad topic area this concept fits into.")
#     target_audience: Optional[str] = Field(None, description="The intended audience for this concept.")
#     key_points: List[str] = Field(..., description="Key points or ideas to include in this concept.")
#     potential_angles: List[str] = Field(default_factory=list, description="Potential angles or perspectives for this concept.")

# class ConceptListSchema(BaseModel):
#     """
#     Defines the structure for a list of content concepts.
#     """
#     concepts: List[ConceptSchema] = Field(..., description="List of content concepts.")


workflow_graph_schema = {
  "nodes": {
        # --- 1. Input Node ---
        "input_node": {
            "node_id": "input_node",
            "node_name": "input_node",
            "node_config": {},
            "dynamic_output_schema": {
                    "fields": {
                        "past_context_posts_limit": { "type": "int", "required": False, "default": PAST_CONTEXT_POSTS_LIMIT, "description": f"Max number of combined posts (drafts + scraped) to use for context (default: {PAST_CONTEXT_POSTS_LIMIT})."},
                        "user_input": { "type": "str", "required": True, "description": "User's input text describing the content idea or topic."},
                        "entity_username": {"type": "str", "required": True},
                    }
            }
                # Outputs: past_context_posts_limit, user_input, entity_username -> $graph_state
        },

        # --- 2. Load Customer Context Documents and Scraped Posts (Single Node) ---
        "load_all_context_docs": {
            "node_id": "load_all_context_docs",
            "node_name": "load_customer_data",
            "node_config": {
                "load_paths": [
                    {
                        "filename_config": {
                            "input_namespace_field_pattern": USER_DNA_NAMESPACE_TEMPLATE, 
                            "input_namespace_field": "entity_username",
                            "static_docname": USER_DNA_DOCNAME,
                        },
                        "output_field_name": "user_dna"
                    },
                    {
                        "filename_config": {
                            "input_namespace_field_pattern": LINKEDIN_SCRAPING_NAMESPACE_TEMPLATE, 
                            "input_namespace_field": "entity_username",
                            "static_docname": LINKEDIN_POST_DOCNAME,
                        },
                        "output_field_name": "scraped_posts"
                    },
                ],
                "global_is_shared": False,
                "global_is_system_entity": False,
                "global_schema_options": {"load_schema": False}
            },
            # Reads: entity_username (from input_node via edge mapping)
            # Writes: user_dna, scraped_posts -> $graph_state
        },

        # --- 3. Load Latest User Draft Posts ---
        "load_draft_posts": {
        "node_id": "load_draft_posts",
        "node_name": "load_multiple_customer_data", # Use the multi-loader node
        "node_config": {
            "namespace_pattern": CONTENT_DRAFT_NAMESPACE_TEMPLATE,
            "namespace_pattern_input_path": "entity_username",
            "include_shared": False,        # User-specific drafts only
            "include_user_specific": True,
            "include_system_entities": False,
            # Pagination and Sorting (Inputs mapped from state)
            "skip": 0,
            "limit": PAST_CONTEXT_POSTS_LIMIT, # Mapped from draft_posts_limit input
            "sort_by": "updated_at",
            "sort_order": "desc",

            # Loading options (default)
            "global_version_config": None, # Load active version if versioned
            "global_schema_options": {"load_schema": False,},

            # Output field name
            "output_field_name": "draft_posts" # The list will be under this key
        },
        #   "dynamic_output_schema": { # Define expected output
        #       "fields": {
        #           "draft_posts": { "type": "list", "required": True, "description": "List of loaded user draft posts." },
        #           "load_metadata": { "type": "dict", "required": True, "description": "Metadata about the loading operation."}
        #       }
        #   }
        # Reads: user_id (for filtering/permissions), draft_posts_limit (for config.limit) from state
        # Writes: draft_posts -> $graph_state
        },

        # --- 4. Merge Posts, Compute Limit, Prepare Generation Context ---
        "prepare_generation_context": {
        "node_id": "prepare_generation_context",
        "node_name": "merge_aggregate", # Use merge_aggregate to combine multiple sources
        "enable_node_fan_in": True, # Wait for all data loads before proceeding
        "node_config": {
            "operations": [
            # Operation 1: Merge Drafts and Scraped Posts and limit the result
            {
                "output_field_name": "final_merged_posts_for_prompt",
                # Order matters for priority (draft posts first, then scraped posts)
                "select_paths": ["draft_posts", "scraped_posts"], # Inputs from state
                "merge_strategy": {
                    "map_phase": {"unspecified_keys_strategy": "ignore"}, # Only care about merging lists
                    "reduce_phase": {
                        "default_reducer": "extend", # Combine the two lists
                        "error_strategy": "fail_node"
                    },
                    # Add transformation to limit the number of posts
                    "post_merge_transformations": {
                        "final_merged_posts_for_prompt": {
                            "operation_type": "limit_list", 
                            "operand_path": "past_context_posts_limit" # Get limit value from input
                        }
                    },
                    "transformation_error_strategy": "skip_operation"
                },
                "merge_each_object_in_selected_list": False # Treat lists as atomic values to be EXTENDed
            },
            ]
        },
        # Reads: loaded_draft_posts, loaded_scraped_posts, loaded_context_docs_list, weeks_to_generate, past_context_posts_limit (from state)
        # Writes: merged_data containing final_merged_posts_for_prompt and total_briefs_needed -> $graph_state
        },

        # --- 3. Interpret User Input ---
        "interpret_user_input": {
            "node_id": "interpret_user_input",
            "node_name": "llm",
            "node_config": {
                "llm_config": {
                    "model_spec": {"provider": LLM_PROVIDER, "model": GENERATION_MODEL},
                    "temperature": LLM_TEMPERATURE,
                    "max_tokens": LLM_MAX_TOKENS
                },
                "output_schema": {
                    "schema_definition": USER_INPUT_INTERPRETATION_SCHEMA
                },
                "default_system_prompt": USER_INPUT_INTERPRETATION_SYSTEM_PROMPT
            }
        },

        # --- 4. Construct User Input Interpretation Prompt ---
        "construct_user_input_interpretation_prompt": {         # Founder A can you check this node? we are not getting input from the previous node in the context - "interpreted_user_input"
            "node_id": "construct_user_input_interpretation_prompt",
            "node_name": "prompt_constructor",
            "node_config": {
                "prompt_templates": {
                    "interpretation_prompt": {
                        "id": "interpretation_prompt",
                        "template": USER_INPUT_INTERPRETATION_USER_PROMPT,
                        "variables": {
                            "user_input": None,
                            "user_dna": None,
                            "merged_posts": None
                        },
                        "construct_options": {
                            "user_input": "user_input",
                            "user_dna": "user_dna",
                            "merged_posts": "merged_posts"
                        }
                    }
                }
            }
        },

        # --- 9. Construct Brief Prompt (Inside Map Branch) ---
        "construct_initial_concepts_prompt": {
            "node_id": "construct_initial_concepts_prompt",
            "node_name": "prompt_constructor",
            "enable_node_fan_in": True,  # Wait for all data loads before proceeding
            "node_config": {
                "prompt_templates": {
                    "initial_concepts_user_prompt": {
                        "id": "initial_concepts_user_prompt",
                        "template": INITIAL_CONCEPTS_USER_PROMPT,
                        "variables": {
                            "interpreted_user_input": None,
                            "user_dna": None,
                            "merged_posts": None,
                        },
                        "construct_options": {
                            "interpreted_user_input": "interpreted_user_input",
                            "user_dna": "user_dna",
                            "merged_posts": "merged_posts",
                        }
                    },
                    "concepts_system_prompt": {
                        "id": "concepts_system_prompt",
                        "template": INITIAL_CONCEPTS_SYSTEM_PROMPT,
                        "variables": { "schema": json.dumps(CONCEPTS_SCHEMA, indent=2) },
                        "construct_options": {}
                    }
                }
            },
        },

        # --- 10. Generate Concepts (LLM - Inside Map Branch) ---
        "generate_concepts": {
            "node_id": "generate_concepts",
            "node_name": "llm",
            "node_config": {
                "llm_config": {
                    "model_spec": {"provider": LLM_PROVIDER, "model": GENERATION_MODEL},
                    "temperature": LLM_TEMPERATURE,
                    "max_tokens": LLM_MAX_TOKENS
                },
                "output_schema": {
                    "schema_definition": CONCEPTS_SCHEMA
                },
            }
        },

        # --- 5. Store Concepts ---
        "store_concepts": {
            "node_id": "store_concepts",
            "node_name": "store_customer_data",
            "node_config": {
                    "global_versioning": {
                        "is_versioned": CONCEPT_IS_VERSIONED,
                        "operation": "upsert_versioned", # Must not exist yet
                    },
                    "store_configs": [
                        {
                            "input_field_path": "structured_output", # Field name in node input containing the value to save
                            "target_path": {
                                "filename_config": {
                                    "input_namespace_field_pattern": CONCEPT_NAMESPACE_TEMPLATE, 
                                    "input_namespace_field": "entity_username",
                                    "static_docname": CONCEPT_DOCNAME, # Field in node's input containing the value
                                }
                            },
                            "generate_uuid": True,
                        }
                    ]
                }
            },

        # --- 6. Human Review ---
        "capture_user_choice": {
            "node_id": "capture_user_choice",
            "node_name": "hitl_node__default",
            "node_config": {}, # Config removed as base HITLNode ignores it
            "dynamic_output_schema": {
                "fields": {
                    "approval_status": { 
                        "type": "enum", 
                        "enum_values": ["regenerate", "restart_from_concept_generation", "select_concepts"],   # TODO: support select only 1 concept for now
                        "required": True, 
                        "description": "User action choice" 
                    },
                    "feedback_text": { 
                        "type": "str", 
                        "required": False, 
                        "description": "Optional feedback for regeneration" 
                    },
                    "selected_concepts": {
                        "type": "list",
                        "items_type": "str",
                        "required": False,
                        "description": "List of concept_ids the user selected if approval_status is 'select_concepts'"
                    }
                }
            }
        },

        # --- 7. Route Based on Approval ---
        "route_on_user_choice": {
            "node_id": "route_on_user_choice",
            "node_name": "router_node",
            "node_config": {
                "choices": ["construct_concepts_regeneration_prompt", "output_node", "filter_selected_concepts"],
                "allow_multiple": False,
                "choices_with_conditions": [
                {
                    "choice_id": "construct_concepts_regeneration_prompt",
                    "input_path": "user_choice_action",
                    "target_value": "regenerate"
                },
                {
                    "choice_id": "output_node",
                    "input_path": "user_choice_action",
                    "target_value": "restart_from_concept_generation"
                },
                {
                    "choice_id": "filter_selected_concepts",
                    "input_path": "user_choice_action",
                    "target_value": "select_concepts"
                }
                ]
            }
        },

        # --- Construct Additional Concepts Prompt ---
        "construct_concepts_regeneration_prompt": {
            "node_id": "construct_concepts_regeneration_prompt",
            "node_name": "prompt_constructor",
            "node_config": {
                "prompt_templates": {
                "additional_concepts_prompt": {
                    "id": "additional_concepts_prompt",
                    "template": ADDITIONAL_CONCEPTS_USER_PROMPT,
                    "variables": {
                        "feedback_text": None
                    },
                    "construct_options": {
                        "feedback_text": "current_feedback_text"
                    }
                },
                }
            }
        },

        # --- Filter Selected Concepts ---
        "filter_selected_concepts": {
            "node_id": "filter_selected_concepts",
            "node_name": "filter_data",
            "node_config": {
                "targets": [
                    {
                        "filter_target": "concepts.concepts",  # Target the concepts list
                        "condition_groups": [
                            {
                                "conditions": [
                                    {
                                        "field": "concepts.concepts.concept_id",
                                        "operator": "equals_any_of",
                                        "value_path": "selected_concepts"
                                    }
                                ]
                            }
                        ],
                        "filter_mode": "allow"  # Only allow concepts that match the condition
                    }
                ]
            }
        },

        # --- 9. Construct Brief Prompt (Inside Map Branch) ---
        "construct_content_brief_prompt": {
            "node_id": "construct_content_brief_prompt",
            "node_name": "prompt_constructor",
            "node_config": {
                "prompt_templates": {
                    "brief_user_prompt": {
                        "id": "brief_user_prompt",
                        "template": BRIEF_USER_PROMPT_TEMPLATE,
                        "variables": {
                            "selected_concepts": None,
                            "user_dna": None,
                            "merged_posts": None,
                            "user_input": None
                        },
                        "construct_options": {
                            "selected_concepts": "selected_concepts.concepts",
                            "user_dna": "user_dna",
                            "merged_posts": "merged_posts",
                            "user_input": "user_input"
                        }
                    },
                    "brief_system_prompt": {
                        "id": "brief_system_prompt",
                        "template": BRIEF_SYSTEM_PROMPT_TEMPLATE,
                        "variables": { "schema": json.dumps(BRIEF_LLM_OUTPUT_SCHEMA, indent=2) },
                        "construct_options": {}
                    }
                }
            }
        },

        # --- 10. Generate Brief (LLM - Inside Map Branch) ---
        "generated_content_brief": {
            "node_id": "generated_content_brief",
            "node_name": "llm",
            "node_config": {
                "llm_config": {
                    "model_spec": {"provider": LLM_PROVIDER, "model": GENERATION_MODEL},
                    "temperature": LLM_TEMPERATURE,
                    "max_tokens": LLM_MAX_TOKENS
                },
                "output_schema": {
                    "schema_definition": BRIEF_LLM_OUTPUT_SCHEMA,
                    "convert_loaded_schema_to_pydantic": False
                },
            }
        },

        # --- 11. Store Generated Brief (After Map Completes) ---
        "save_content_brief": {
            "node_id": "save_content_brief",
            "node_name": "store_customer_data", # Store the final list
            "node_config": {
                "global_versioning": { "is_versioned": CONTENT_BRIEF_IS_VERSIONED, "operation": "upsert_versioned" },
                "global_is_shared": False,
                "store_configs": [
                    {
                        # Store the final content brief
                        "input_field_path": "updated_brief", # Mapped from LLM output
                        "target_path": {
                            "filename_config": {
                                "input_namespace_field_pattern": CONTENT_BRIEF_NAMESPACE_TEMPLATE, 
                                "input_namespace_field": "entity_username",
                                "static_docname": CONTENT_BRIEF_DOCNAME, # Use static docname instead of input field
                            }
                        },
                        "versioning": {
                            "is_versioned": CONTENT_BRIEF_IS_VERSIONED,
                            "operation": "upsert_versioned",
                            "version": CONTENT_BRIEF_DEFAULT_VERSION
                        },
                        "generate_uuid": True, # Generate UUID for the brief - automatically adds to create_only_fields
                    }
                ],
            }
        },

        # --- 12. Store Concepts with Brief ID ---
        "save_concepts_with_brief_id": {
            "node_id": "save_concepts_with_brief_id",
            "node_name": "store_customer_data",
            "node_config": {
                "global_versioning": { "is_versioned": CONCEPT_IS_VERSIONED, "operation": "upsert_versioned" },
                "global_is_shared": False,
                "store_configs": [
                    {
                        # Store the concepts with brief_id from first save operation
                        "input_field_path": "selected_concepts.concepts",
                        "target_path": {
                            "filename_config": {
                                "input_namespace_field_pattern": CONCEPT_NAMESPACE_TEMPLATE, 
                                "input_namespace_field": "entity_username",
                                "static_docname": CONCEPT_DOCNAME,
                            }
                        },
                        "generate_uuid": True,
                        "extra_fields": [
                            {
                                # Use the UUID from the first save operation's passthrough_data
                                "src_path": "first_node_data.updated_brief.uuid",
                                "dst_path": "brief_id"
                            }
                        ],
                        "versioning": {
                            "is_versioned": CONCEPT_IS_VERSIONED,
                            "operation": "upsert_versioned",
                        }
                    }
                ],
            }
        },

        # --- 13. Output Node ---
        "output_node": {
            "node_id": "output_node",
            "node_name": "output_node",
            "node_config": {},
            # "dynamic_input_schema": { # Define expected final inputs
            #     "fields": {
            #         "final_briefs_list": { "type": "list", "required": True, "description": "The complete list of generated content briefs." },
            #         "brief_paths_processed": { "type": "list", "required": False, "description": "Confirmation/path from the storage operation." }
            #     }
            # }
            # Reads: updated_brief (mapped to final_briefs_list), paths_processed (mapped to save_confirmation)
        },




    },

    # --- Edges Defining Data Flow ---
    "edges": [
        # --- Initial Setup ---
        # Input -> State: Store initial inputs globally
        { "src_node_id": "input_node", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "past_context_posts_limit", "dst_field": "past_context_posts_limit" },
            { "src_field": "user_input", "dst_field": "user_input" },
            { "src_field": "entity_username", "dst_field": "entity_username" },
          ]
        },
        
        # Input -> Load operations
        { "src_node_id": "input_node", "dst_node_id": "load_all_context_docs", "mappings": [
            { "src_field": "entity_username", "dst_field": "entity_username" },
          ], "description": "Trigger context docs loading."
        },


        { "src_node_id": "input_node", "dst_node_id": "load_draft_posts",
            "mappings": [
                { "src_field": "entity_username", "dst_field": "entity_username" },
            ],
            },

        # --- State Updates from Loaders ---
        { "src_node_id": "load_all_context_docs", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "user_dna", "dst_field": "user_dna"},
            { "src_field": "scraped_posts", "dst_field": "scraped_posts"}
          ]
        },

        { "src_node_id": "load_draft_posts", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "draft_posts", "dst_field": "draft_posts"}
          ]
        },

        { "src_node_id": "load_all_context_docs", "dst_node_id": "prepare_generation_context"},
        
        { "src_node_id": "load_draft_posts", "dst_node_id": "prepare_generation_context"},

        # --- Mapping State to Context Prep Node ---
        { "src_node_id": "$graph_state", "dst_node_id": "prepare_generation_context", "mappings": [
            { "src_field": "draft_posts", "dst_field": "draft_posts" },
            { "src_field": "scraped_posts", "dst_field": "scraped_posts" },
            { "src_field": "past_context_posts_limit", "dst_field": "past_context_posts_limit" },
        ]
        },

        # --- User Input Interpretation Path ---
        { "src_node_id": "prepare_generation_context", "dst_node_id": "construct_user_input_interpretation_prompt",
            "mappings": [
                { "src_field": "merged_data", "dst_field": "merged_posts" },
            ]
        },

        { "src_node_id": "$graph_state", "dst_node_id": "construct_user_input_interpretation_prompt", "mappings": [
            { "src_field": "user_input", "dst_field": "user_input" },
            { "src_field": "user_dna", "dst_field": "user_dna" },
          ]
        },

        { "src_node_id": "construct_user_input_interpretation_prompt", "dst_node_id": "interpret_user_input", "mappings": [
            { "src_field": "interpretation_prompt", "dst_field": "user_prompt" }
          ]
        },

        # --- State -> Interpret User Input (Message History) ---
        { "src_node_id": "$graph_state", "dst_node_id": "interpret_user_input", "mappings": [
            { "src_field": "interpret_user_input_messages_history", "dst_field": "messages_history"}
          ]
        },

        { "src_node_id": "interpret_user_input", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "structured_output", "dst_field": "interpreted_user_input" },
            { "src_field": "current_messages", "dst_field": "interpret_user_input_messages_history"}
          ]
        },

        # --- Initial Concepts Prompt Construction (Now depends on interpreted input) ---
        { "src_node_id": "interpret_user_input", "dst_node_id": "construct_initial_concepts_prompt", "mappings": [
            { "src_field": "structured_output", "dst_field": "interpreted_user_input" }
          ]
        },

        { "src_node_id": "$graph_state", "dst_node_id": "construct_initial_concepts_prompt", "mappings": [
            { "src_field": "user_dna", "dst_field": "user_dna" },
            { "src_field": "merged_posts", "dst_field": "merged_posts" },
          ]
        },

        # --- Map Iteration -> Construct Prompt (Private Edge) ---
        { "src_node_id": "prepare_generation_context", "dst_node_id": "construct_initial_concepts_prompt",
            "mappings": [
                { "src_field": "merged_data", "dst_field": "merged_posts" },
            ]
        },

        { "src_node_id": "prepare_generation_context", "dst_node_id": "$graph_state",
            "mappings": [
                { "src_field": "merged_data", "dst_field": "merged_posts" },
            ]
        },

        # --- Construct Prompt → Generate Concepts ---
        { "src_node_id": "construct_initial_concepts_prompt", "dst_node_id": "generate_concepts", "mappings": [
            { "src_field": "initial_concepts_user_prompt", "dst_field": "user_prompt"},
            { "src_field": "concepts_system_prompt", "dst_field": "system_prompt"}
          ], "description": "Send prompts to LLM for concept generation."
        },

        # --- State -> Generate Concepts ---
        { "src_node_id": "$graph_state", "dst_node_id": "generate_concepts", "mappings": [
            { "src_field": "generate_concepts_messages_history", "dst_field": "messages_history"}
          ]
        },

        # --- Generate Concepts -> Store & State ---
        { "src_node_id": "generate_concepts", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "structured_output", "dst_field": "current_generated_concepts"},
            { "src_field": "current_messages", "dst_field": "generate_concepts_messages_history"}
          ]
        },

        { "src_node_id": "generate_concepts", "dst_node_id": "store_concepts", "mappings": [
            { "src_field": "structured_output", "dst_field": "structured_output"}
          ]
        },

        # --- State -> Store Concepts ---
        { "src_node_id": "$graph_state", "dst_node_id": "store_concepts", "mappings": [
            { "src_field": "initial_brief", "dst_field": "initial_brief"},
            { "src_field": "entity_username", "dst_field": "entity_username"},
          ]
        },

        # --- Store Concepts -> User Choice ---
        { "src_node_id": "store_concepts", "dst_node_id": "capture_user_choice", "mappings": [
            { "src_field": "paths_processed", "dst_field": "draft_paths_processed"}
          ]
        },

        # --- State -> User Choice ---
        { "src_node_id": "$graph_state", "dst_node_id": "capture_user_choice", "mappings": [
            { "src_field": "current_generated_concepts", "dst_field": "concepts_for_review"}
          ]
        },

        # --- User Choice -> Route ---
        { "src_node_id": "capture_user_choice", "dst_node_id": "route_on_user_choice", "mappings": [
            { "src_field": "approval_status", "dst_field": "user_choice_action"},
          ]
        },

        # --- User Choice -> State ---
        { "src_node_id": "capture_user_choice", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "feedback_text", "dst_field": "current_feedback_text"},
            { "src_field": "selected_concepts", "dst_field": "user_selected_concepts"}
          ]
        },

        # --- Route -> Paths ---
        { "src_node_id": "route_on_user_choice", "dst_node_id": "construct_concepts_regeneration_prompt", "description": "Route to regenerate concepts if requested." },
        { "src_node_id": "route_on_user_choice", "dst_node_id": "output_node", "description": "Route to output if going back." },
        { "src_node_id": "route_on_user_choice", "dst_node_id": "filter_selected_concepts", "description": "Route to filter if concepts selected." },

        # --- Regeneration Prompt -> Generate Concepts ---
        { "src_node_id": "$graph_state", "dst_node_id": "construct_concepts_regeneration_prompt", "mappings": [
            { "src_field": "current_feedback_text", "dst_field": "current_feedback_text"}
          ]},

        { "src_node_id": "construct_concepts_regeneration_prompt", "dst_node_id": "generate_concepts", "mappings": [
            { "src_field": "additional_concepts_prompt", "dst_field": "user_prompt"}
          ]
        },

        # --- State -> Filter ---
        { "src_node_id": "$graph_state", "dst_node_id": "filter_selected_concepts", "mappings": [
            { "src_field": "current_generated_concepts", "dst_field": "concepts"},
            { "src_field": "user_selected_concepts", "dst_field": "selected_concepts"}
          ]
        },

        # --- Filter -> Update Content Brief Prompt ---
        { "src_node_id": "filter_selected_concepts", "dst_node_id": "construct_content_brief_prompt", "mappings": [
            { "src_field": "filtered_data", "dst_field": "selected_concepts"}
          ]
        },

        # --- Filter -> Save Updated Content Brief (to also save selected concepts) ---
        { "src_node_id": "filter_selected_concepts", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "filtered_data", "dst_field": "selected_concepts"}
          ]
        },

        # --- State -> Update Content Brief Prompt ---
        { "src_node_id": "$graph_state", "dst_node_id": "construct_content_brief_prompt", "mappings": [
            { "src_field": "user_dna", "dst_field": "user_dna" },
            { "src_field": "merged_posts", "dst_field": "merged_posts"},
            { "src_field": "user_input", "dst_field": "user_input"}
          ]
        },

        # --- Update Content Brief Prompt -> Generate Updated Brief ---
        { "src_node_id": "construct_content_brief_prompt", "dst_node_id": "generated_content_brief", "mappings": [
            { "src_field": "brief_user_prompt", "dst_field": "user_prompt"},
            { "src_field": "brief_system_prompt", "dst_field": "system_prompt"}
          ]
        },

        # --- State -> Generate Content Brief (Message History) ---
        { "src_node_id": "$graph_state", "dst_node_id": "generated_content_brief", "mappings": [
            { "src_field": "generated_content_brief_messages_history", "dst_field": "messages_history"}
          ]
        },

        # --- Generate Updated Brief -> State ---
        { "src_node_id": "generated_content_brief", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "structured_output", "dst_field": "updated_brief"},
            { "src_field": "current_messages", "dst_field": "generated_content_brief_messages_history"}
          ]
        },

        # --- Generate Updated Brief -> Save ---
        { "src_node_id": "generated_content_brief", "dst_node_id": "save_content_brief", "mappings": [
            { "src_field": "structured_output", "dst_field": "updated_brief"}
          ]
        },

        # --- State -> Save Brief ---
        { "src_node_id": "$graph_state", "dst_node_id": "save_content_brief", "mappings": [
            { "src_field": "user_input", "dst_field": "user_input"},
            { "src_field": "entity_username", "dst_field": "entity_username"}
        ]},

        # --- Save Brief -> Save Concepts ---
        { "src_node_id": "save_content_brief", "dst_node_id": "save_concepts_with_brief_id", "mappings": [
            { "src_field": "passthrough_data", "dst_field": "first_node_data"}
          ]
        },

        { "src_node_id": "save_content_brief", "dst_node_id": "$graph_state", "mappings": [
            { "src_field": "paths_processed", "dst_field": "final_brief_paths_processed"}
          ]
        },

        # --- State -> Save Concepts ---
        { "src_node_id": "$graph_state", "dst_node_id": "save_concepts_with_brief_id", "mappings": [
            { "src_field": "selected_concepts", "dst_field": "selected_concepts"},
            { "src_field": "entity_username", "dst_field": "entity_username"}
        ]},

        # --- Save Concepts -> Output ---
        { "src_node_id": "save_concepts_with_brief_id", "dst_node_id": "output_node", "mappings": [
            { "src_field": "paths_processed", "dst_field": "concept_paths_processed"}
          ]
        },

        # --- State -> Output ---
        { "src_node_id": "$graph_state", "dst_node_id": "output_node", "mappings": [
            { "src_field": "updated_brief", "dst_field": "final_brief_content"},
            { "src_field": "selected_concepts", "dst_field": "selected_concepts"},
            { "src_field": "final_brief_paths_processed", "dst_field": "final_brief_paths_processed"}
          ]
        },
    ],

    # --- Define Start and End ---
    "input_node_id": "input_node",
    "output_node_id": "output_node",

    # --- State Reducers ---
    "metadata": {
        "$graph_state": {
            "reducer": {
                # NOTE: If you set collect_values reducer here, it distorts / nests the concepts structure and fails the FILTER NODE!
                # "current_generated_concepts": "collect_values",
                "interpret_user_input_messages_history": "add_messages",
                "generate_concepts_messages_history": "add_messages", 
                "generated_content_brief_messages_history": "add_messages"
            }
        }
    }
}


# --- Test Execution Logic ---
async def main_test_concept_to_brief_workflow():
    """
    Test for Concept to Brief Workflow.
    
    This function sets up test data, executes the workflow, and validates the output.
    The workflow takes an initial brief, generates content ideas, allows for user selection,
    and then creates a refined content brief based on the selected ideas.
    """
    test_name = "Concept to Brief Workflow Test"
    print(f"--- Starting {test_name} --- ")

    # Example Inputs
    test_entity_username = "test_entity"
    
    test_inputs = {
        "user_input": "I want to create a post about the impact of AI on digital marketing strategies, focusing on how it's changing the way we approach customer engagement and personalization.",
        "past_context_posts_limit": 20,
        "entity_username": test_entity_username
    }
    # print(json.dumps(test_inputs, indent=4))
    # return

    # Define setup documents
    setup_docs = [
        # User DNA Document
        {
            'namespace': USER_DNA_NAMESPACE_TEMPLATE.format(item=test_entity_username), 
            'docname': USER_DNA_DOCNAME,
            'initial_data': {
                "professional_identity": {
                    "full_name": "Test User",
                    "job_title": "Founder and CEO",
                    "industry_sector": "Business Consulting and Services (RevOps/Sales Operations)",
                    "company_name": "Revology Consulting",
                    "company_size": "Small (early‑stage startup)",
                    "years_of_experience": 10,
                    "professional_certifications": [],
                    "areas_of_expertise": [
                        "RevOps consulting and implementation",
                        "Sales operations strategy and enablement",
                        "Tech stack assessment, consolidation, and optimization",
                        "CRM expertise (Salesforce, HubSpot implementation and optimization)",
                        "Sales engagement tools (Outreach, SalesLoft)",
                        "Business process optimization and automation",
                        "Metrics identification and tracking",
                        "Email personalization and outreach strategies",
                        "Cross‑departmental alignment (sales and marketing)",
                        "Tech stack security auditing and vulnerability assessment",
                        "Leading vs. lagging indicator frameworks for business measurement"
                    ],
                    "career_milestones": [
                        "Founded Revology Consulting (December 2024)",
                        "Senior RevOps Consultant at Skaled Consulting (2021‑Present)",
                        "Worked with ~80 different clients over 5 years on RevOps",
                        "Worked with notable companies including OpenAI, UiPath, SurveyMonkey",
                        "Roles at Groupon, Microsoft, Verizon, Zebra Technologies",
                        "Scientific background with transition to operations roles"
                    ],
                    "professional_bio": "Test User is the Founder and CEO of Revology Consulting, a firm specializing in helping companies streamline their revenue operations. With an analytical foundation (Master's in Genetics and Genetic Manipulation) and over a decade in operations roles, she helps businesses optimize their tech stack, sales processes, and revenue operations to drive efficiency and growth. Her expertise spans multiple industries, company sizes, and global markets, giving her unique insights into operational excellence across diverse business contexts."
                },
                "linkedin_profile_analysis": {
                    "follower_count": 1495,
                    "connection_count": None,
                    "profile_headline_analysis": "All things RevOps | Founder & CEO | Simplifying Processes and Demystifying Tech",
                    "about_section_summary": "Focuses on expertise in revenue operations, helping companies integrate and optimize tech stacks, sales processes, and enablement strategies to drive efficiency and scalability. Emphasizes enhancing workflows, building scalable systems, and driving measurable results with focus on reducing inefficiencies and creating data‑driven processes.",
                    "engagement_metrics": {
                        "average_likes_per_post": 76,
                        "average_comments_per_post": 40,
                        "average_shares_per_post": 0
                    },
                    "top_performing_content_pillars": [
                        "Business & Entrepreneurship",
                        "Workplace Culture & Employee Experience",
                        "Community & Networking"
                    ],
                    "content_posting_frequency": "Inconsistent historically; moving forward: RevOps education/brand awareness, weekly Founder Friday, tool spotlights, and event recaps (2 per week)",
                    "content_types_used": [
                        "Text posts with emoji bullets",
                        "Milestone updates with specific metrics",
                        "Personal narratives with reflections",
                        "Lists with emoji markers",
                        "Short, direct posts for simple updates",
                        "Security‑focused content with lock emojis (🔓)",
                        "Contrast formats highlighting what works vs. what doesn't",
                        "Relatable analogies connecting with everyday experiences"
                    ],
                    "network_composition": [
                        "Predominantly US‑based connections (~90%)",
                        "Connections in UK, Europe, and globally (including Singapore)",
                        "Mix of B2B and B2C companies",
                        "Focus on companies using Salesforce and HubSpot",
                        "Strong ties to RevOps, sales operations, and SaaS sectors",
                        "Growing network of agency owners"
                    ]
                },
                "brand_voice_and_style": {
                    "communication_style": "Straightforward, authoritative yet approachable",
                    "tone_preferences": [
                        "Enthusiastic",
                        "Confident but not overly technical",
                        "Occasionally vulnerable/authentic",
                        "Celebratory for achievements",
                        "Reflective when sharing lessons",
                        "Definitive on security vulnerabilities",
                        "Direct in content body"
                    ],
                    "vocabulary_level": "Professional but accessible; uses industry‑specific terms without excessive jargon; occasionally employs scientific references, relatable analogies, and humor with cultural references.",
                    "sentence_structure_preferences": "Mix of short declarative statements for impact and longer explanatory sentences for complex topics; questions mainly used as CTAs at post ends; bulleted lists; preference for direct statements in body.",
                    "content_format_preferences": [
                        "Emoji‑bulleted lists",
                        "Achievement markers with visual indicators",
                        "Short paragraphs (2‑3 sentences)",
                        "Clear headline formats for announcements",
                        "\"Statement‑Problem‑Solution\" advice structure",
                        "Contrasting sections with emojis (✅ vs. 🚫)",
                        "Leading vs. lagging indicator differentiation"
                    ],
                    "emoji_usage": "Frequent emoji use, especially in milestone posts (average 14.3 per post in Business & Entrepreneurship); common emojis include 🎉, ✅, 🚀, ❤️, 🔓; 4‑14 emojis per post depending on content.",
                    "hashtag_usage": "Moderate; placed at post ends; present in 55‑62% of posts; uses relevant industry tags; strong preference for #WhoStillHasYourPasswords in security content.",
                    "storytelling_approach": "Personal founder narratives with practical takeaways; celebratory announcements; personal declarations for community posts; combines vulnerability with expertise; uses plant care and scientific metaphors for business."
                },
                "content_strategy_goals": {
                    "primary_goal": "Increase brand awareness for Revology Consulting and position Mahak as a trusted RevOps expert",
                    "secondary_goals": [
                        "Educate audience about RevOps, especially in Europe",
                        "Document and share founder journey and weekly lessons",
                        "Develop strategic partnerships with complementary businesses",
                        "Generate business through referrals",
                        "Grow Mahak's personal brand",
                        "Establish reputation for tech stack security expertise"
                    ],
                    "target_audience_demographics": "SMBs (<5 M USD revenue, <200 employees) primarily B2B; similar B2C companies; users of Salesforce and HubSpot; agency owners",
                    "ideal_reader_personas": [
                        "SMB decision‑makers needing RevOps expertise",
                        "Operations leaders optimizing tech stack",
                        "Founders focused on operational excellence",
                        "Sales and marketing leaders seeking alignment"
                    ],
                    "audience_pain_points": [
                        "Poor tech stack optimization",
                        "Bad email personalization practices",
                        "Measuring wrong metrics",
                        "Lack of sales and marketing alignment",
                        "Excessive manual processes",
                        "Security risks from unmonitored tool access",
                        "Over‑focus on lagging indicators",
                        "Neglected security risks in tech stack integrations",
                        "Unmonitored tool access security vulnerabilities",
                        "Customer engagement patterns not tracked properly",
                        "Using insecure platforms for sensitive data"
                    ],
                    "value_proposition_to_audience": "Expertise in identifying and solving operational inefficiencies; tech stack optimization to reduce redundancy and cost; proper metrics selection; task automation; global perspective; practical advice; security auditing expertise; frameworks for leading indicators.",
                    "call_to_action_preferences": [
                        "Direct engagement in comments",
                        "Open invitations for connections",
                        "Occasional discussion questions"
                    ],
                    "content_pillar_themes": [
                        "RevOps education and best practices",
                        "Founder journey insights (Founder Friday)",
                        "Tool spotlights and collaborations",
                        "Event recaps and insights",
                        "Tech stack security and vulnerability assessments",
                        "Leading vs. lagging indicator frameworks"
                    ],
                    "topics_of_interest": [
                        "Tech stack audits and optimization",
                        "Metrics selection and tracking",
                        "Email personalization strategies",
                        "Sales and marketing alignment challenges and solutions",
                        "Automation opportunities and implementation",
                        "Data security in operations",
                        "Tool comparison and selection criteria",
                        "Revology product developments (speedy setup)",
                        "Tech stack security vulnerabilities",
                        "Integration security risks with CRMs",
                        "Leading vs. lagging indicators contrast",
                        "Plant care metaphors for business growth",
                        "Client feedback collection and implementation"
                    ]
                },
                "personal_context": {
                    "personal_values": [
                        "Efficiency and optimization",
                        "Authenticity and cultural pride",
                        "Cross‑cultural understanding and global perspective",
                        "Analytical thinking",
                        "Continuous learning and knowledge sharing",
                        "Continuous improvement through feedback",
                        "Growth through consistency and patience"
                    ],
                    "professional_mission_statement": "Helping companies streamline revenue operations by integrating and optimizing tech stack and processes to reduce inefficiencies, empower teams, and create data‑driven processes that support long‑term growth.",
                    "content_creation_challenges": [
                        "Consistency and structure in content",
                        "Strategic approach to content pillars",
                        "Time management balancing content creation with running business",
                        "Desire for specific, detailed feedback on content",
                        "Rapid implementation of constructive feedback",
                        "Appreciation for high ratings with actionable feedback"
                    ],
                    "personal_story_elements_for_content": [
                        "Cultural background and international perspective",
                        "Scientific/analytical foundation (Master's in Genetics)",
                        "Global experience with clients across regions",
                        "Early‑stage founder experiences and challenges",
                        "Plant care and gardening metaphors for business growth",
                        "Scientific method applied to client feedback",
                        "Collecting and implementing feedback via Typeform",
                        "Dropping \"golden nuggets\" during focused training"
                    ],
                    "notable_life_experiences": [
                        "Transition from science to operations roles",
                        "Working across multiple countries and cultures",
                        "Observations of regional work culture differences",
                        "Recent marriage and related cultural traditions",
                        "Connection to plant care and growth enthusiasm"
                    ],
                    "inspirations_and_influences": None,
                    "books_resources_they_reference": None,
                    "quotes_they_resonate_with": None
                },
                "analytics_insights": {
                    "optimal_content_length": "Business & Entrepreneurship ~217 words; Community & Networking ~112; Professional Growth ~127; Sales & Marketing ~87; Workplace Culture ~187; hooks 5–8 words for impact",
                    "audience_geographic_distribution": "~90% US‑based, some UK presence, international reach including Singapore",
                    "engagement_time_patterns": None,
                    "keyword_performance_analysis": "Engagement drivers: \"community\", \"culture\", \"modern outbound\", \"RevOps\", \"Revology Consulting\", security‑related terms, #WhoStillHasYourPasswords, leading/lagging indicators terminology",
                    "competitor_benchmarking": None,
                    "growth_rate_metrics": "7 clients, 3 partnerships, £77,100 closed deals within first 3 months"
                },
                "success_metrics": {
                    "content_performance_kpis": [
                        "Engagement metrics by post type",
                        "Follower growth",
                        "Brand recognition for Revology",
                        "Content quality feedback ratings (9–10/10)"
                    ],
                    "engagement_quality_metrics": [
                        "Comments and meaningful conversations",
                        "Quality engagement from target audience",
                        "Styling preference feedback"
                    ],
                    "conversion_goals": [
                        "Generate new business through referrals",
                        "Establish and grow partnerships",
                        "Drive awareness of Revology's services"
                    ],
                    "brand_perception_goals": [
                        "Establish Revology's market reputation",
                        "Position Mahak as a trusted RevOps expert",
                        "Increase knowledge of RevOps in Europe",
                        "Authoritative yet approachable brand",
                        "Reputation for tech stack security expertise"
                    ],
                    "timeline_for_expected_results": "3–6 months",
                    "benchmarking_standards": "Previous post performance and business growth metrics serve as baseline; content rated on 10‑point feedback scale"
                }
            }, 
            'is_versioned': USER_DNA_IS_VERSIONED, 
            'is_shared': False,
            'initial_version': 'default'  # Required for versioned documents
        },
        # Mock LinkedIn Scraped Posts
        {
            'namespace': LINKEDIN_SCRAPING_NAMESPACE_TEMPLATE.format(item=test_entity_username), 
            'docname': LINKEDIN_POST_DOCNAME,
            'initial_data': [
                {
                    "urn": "post-revops-1",
                    "text": "🔓 Security audit time! Just discovered a client had 47 people with admin access to their Salesforce instance. 47! That's not access management, that's access chaos. ✅ What we fixed: Proper role hierarchy, regular access reviews, automated deprovisioning. 🚫 What we found: Shared passwords, ex-employees still active, no MFA. #WhoStillHasYourPasswords #RevOps #TechStackSecurity",
                    "publish_date": "2024-01-15T10:00:00Z",
                    "reaction_count": 89,
                    "comment_count": 23
                },
                {
                    "urn": "post-revops-2",
                    "text": "🎉 Founder Friday update! Week 3 of Revology Consulting and I'm learning that building systems for clients is very different from building systems for your own business. The irony? I'm great at optimizing other people's tech stacks but spent 2 hours yesterday trying to connect my own CRM to my email tool. 😅 Lesson learned: Even RevOps experts need to practice what they preach. What's one system you know you should optimize but keep putting off? #FounderFriday #RevOps #Entrepreneurship",
                    "publish_date": "2024-01-12T14:30:00Z",
                    "reaction_count": 156,
                    "comment_count": 41
                }
            ], 
            'is_versioned': False,  # Assuming scraped posts are not versioned
            'is_shared': False
        },
        # Mock Draft Posts
        {
            'namespace': CONTENT_DRAFT_NAMESPACE_TEMPLATE.format(item=test_entity_username), 
            'docname': CONTENT_DRAFT_DOCNAME.replace('{_uuid_}', 'draft-1'),
            'initial_data': {
                "title": "Leading vs Lagging Indicators in RevOps",
                "content": "🎯 Stop measuring what happened. Start measuring what's happening. Most RevOps teams are drowning in lagging indicators: ✅ Revenue closed ✅ Deal velocity ✅ Win rates But missing the leading indicators that actually drive those outcomes: 🚀 Pipeline quality scores 🚀 Engagement velocity 🚀 Process adherence rates The difference? Lagging indicators tell you if you hit your target. Leading indicators tell you if you're aiming correctly. What leading indicators are you tracking in your RevOps? #RevOps #Metrics #DataDriven",
                "created_at": "2024-01-20T10:00:00Z",
                "updated_at": "2024-01-21T14:30:00Z",
            }, 
            'is_versioned': CONTENT_DRAFT_IS_VERSIONED, 
            'is_shared': False,
            'initial_version': 'draft'  # Required for versioned documents
        },
        {
            'namespace': CONTENT_DRAFT_NAMESPACE_TEMPLATE.format(item=test_entity_username), 
            'docname': CONTENT_DRAFT_DOCNAME.replace('{_uuid_}', 'draft-2'),
            'initial_data': {
                "title": "Tech Stack Consolidation Reality Check",
                "content": "💡 Your tech stack isn't a collection. It's an ecosystem. Just helped a client reduce their sales tools from 12 to 4. The result? 🎉 40% faster onboarding 🎉 60% fewer integration issues 🎉 £2,400/month in savings The secret wasn't finding the 'perfect' tool. It was finding tools that actually talk to each other. Before consolidating, ask: ✅ Does this tool integrate natively? ✅ Can it replace 2+ existing tools? ✅ Will it scale with our growth? Your tech stack should amplify your team, not complicate their lives. What's one tool you could eliminate today? #TechStack #RevOps #Efficiency",
                "created_at": "2024-01-18T09:15:00Z",
                "updated_at": "2024-01-19T16:45:00Z"
            }, 
            'is_versioned': CONTENT_DRAFT_IS_VERSIONED, 
            'is_shared': False,
            'initial_version': 'draft'  # Required for versioned documents
        },
    ]

    # Define cleanup docs
    cleanup_docs = [
        {'namespace': USER_DNA_NAMESPACE_TEMPLATE.format(item=test_entity_username), 'docname': USER_DNA_DOCNAME, 'is_versioned': USER_DNA_IS_VERSIONED, 'is_shared': False},
        {'namespace': CONCEPT_NAMESPACE_TEMPLATE.format(item=test_entity_username), 'docname': CONCEPT_DOCNAME, 'is_versioned': CONCEPT_IS_VERSIONED, 'is_shared': False},
        {'namespace': CONTENT_BRIEF_NAMESPACE_TEMPLATE.format(item=test_entity_username), 'docname': CONTENT_BRIEF_DOCNAME, 'is_versioned': CONTENT_BRIEF_IS_VERSIONED, 'is_shared': False},
        {'namespace': LINKEDIN_SCRAPING_NAMESPACE_TEMPLATE.format(item=test_entity_username), 'docname': LINKEDIN_POST_DOCNAME, 'is_versioned': False, 'is_shared': False},
    ]

    # Predefined HITL inputs - leaving empty to allow for interactive testing
    # In actual testing, you can provide predefined inputs like:
    # {"approval_status": "select_concepts", "selected_concepts": ["concept_1", "concept_2"]}
    predefined_hitl_inputs = []
    
    # VALID HUMAN INPUTS FOR MANUAL TESTING:
    # {"approval_status": "select_concepts", "selected_concepts": ["concept_01"]}
    # {"approval_status": "regenerate", "feedback_text": "Please generate more contrarian concepts"}
    # {"approval_status": "restart_from_concept_generation"}

    # Output validation function
    async def validate_brief_output(outputs):
        """Validates the workflow output to ensure it meets expected structure and content requirements."""
        assert outputs is not None, "Validation Failed: Workflow returned no outputs."
        assert 'final_brief_content' in outputs, "Validation Failed: 'final_brief_content' missing."
        
        # Validate the content brief structure
        if 'final_brief_content' in outputs:
            brief = outputs['final_brief_content']
            # Check for required fields based on ContentBriefSchema in content_calendar_brief.py
            assert 'title' in brief, "Brief missing required field: title"
            assert 'content_pillar' in brief, "Brief missing required field: content_pillar"
            assert 'core_perspective' in brief, "Brief missing required field: core_perspective"
            assert 'target_audience' in brief and isinstance(brief['target_audience'], dict), "Brief missing or invalid field: target_audience"
            assert 'primary' in brief['target_audience'], "target_audience missing required field: primary"
            
            # Check for key list fields
            assert 'key_messages' in brief and isinstance(brief['key_messages'], list), "Brief missing or invalid field: key_messages"
            assert 'post_objectives' in brief and isinstance(brief['post_objectives'], list), "Brief missing or invalid field: post_objectives"
            assert 'hashtags' in brief and isinstance(brief['hashtags'], list), "Brief missing or invalid field: hashtags"
            
            # Check for structured objects
            assert 'structure_outline' in brief and isinstance(brief['structure_outline'], dict), "Brief missing or invalid field: structure_outline"
            assert 'post_length' in brief and isinstance(brief['post_length'], dict), "Brief missing or invalid field: post_length"
            
            print(f"✓ Final brief validated successfully with title: {brief.get('title', 'unknown')}")
        
        return True

    # Execute the test
    final_run_status_obj, final_run_outputs = await run_workflow_test(
        test_name=test_name,
        workflow_graph_schema=workflow_graph_schema,
        initial_inputs=test_inputs,
        expected_final_status=WorkflowRunStatus.COMPLETED,
        hitl_inputs=predefined_hitl_inputs,
        setup_docs=setup_docs,
        cleanup_docs=cleanup_docs,
        cleanup_docs_created_by_setup=False,
        validate_output_func=validate_brief_output,
        stream_intermediate_results=True,
        poll_interval_sec=5,
        timeout_sec=600
    )

    print(f"--- {test_name} Finished --- ")
    if final_run_outputs and 'final_brief_content' in final_run_outputs:
        brief = final_run_outputs['final_brief_content']
        print(f"Generated Brief Title: {brief.get('title')}")
        print(f"Generated Brief Core Perspective: {brief.get('core_perspective')}")
        print(f"Generated Brief Call to Action: {brief.get('call_to_action')}")
        print(f"Generated Brief Hashtags: {brief.get('hashtags')}")

if __name__ == "__main__":
    try:
        asyncio.run(main_test_concept_to_brief_workflow())
    except KeyboardInterrupt:
        print("\nExecution interrupted.")
    except Exception as e:
        print(f"\nError running test: {e}")

