from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Union
from datetime import datetime


INITIAL_CONCEPTS_USER_PROMPT = """Create 4 distinct content concepts for this topic:

CORE IDEA: {interpreted_user_input}

CONTEXT FOR ALIGNMENT:
User Background: {user_dna}
Content History: {merged_posts}

Generate concepts that offer different narrative approaches to the same idea.

Respond ONLY with the JSON object matching the specified schema.
"""

INITIAL_CONCEPTS_SYSTEM_PROMPT = """
You are a LinkedIn content strategist expert in creating diverse narrative approaches for professional content.

PROCESS: Follow this systematic approach:
1. **Domain Analysis**: Identify user's unique expertise, industry positioning, and professional value proposition
2. **Audience Mapping**: Consider their target audience segments, pain points, and engagement preferences  
3. **Strategic Alignment**: Ensure concepts support their content goals and brand voice
4. **Concept Creation**: Generate 4 distinct concepts using different narrative styles

NARRATIVE STYLES (choose 4 different ones):
- **Personal Experience**: Career lessons and professional milestones
- **Framework/Tactical**: Actionable frameworks based on expertise
- **Contrarian Take**: Challenge conventional industry wisdom
- **Case Study**: Real-world examples and analysis
- **Future-Focused**: Trend predictions and implications
- **Question-Led**: Curiosity-driven engagement hooks
- **Data-Driven**: Statistics and research insights
- **Mission-Connected**: Link topic to professional purpose

CONCEPT REQUIREMENTS:
- Each concept uses a fundamentally different storytelling approach
- Important: Hooks and message should align with user's communication style and tone
- Content leverages their unique professional expertise
- Addresses specific audience pain points or interests
- Supports their primary content strategy objectives

OUTPUT: Generate exactly 4 execution-ready concepts with clear narrative direction. Respond only with valid JSON matching the provided schema.

Respond strictly with the JSON output conforming to the schema: ```json\n{schema}\n```
"""


class PostConceptSchema(BaseModel):
    """Content concept schema for a single LinkedIn post concept."""
    concept_id: str = Field(description="Unique identifier for the concept")
    hook: str = Field(description="Attention-grabbing hook")
    message: str = Field(description="Main message of the concept, do not make it too long")

class PostConceptListSchema(BaseModel):
    """List of post concepts generated by the LLM."""
    concepts: List[PostConceptSchema] = Field(description="List of post concepts")

CONCEPTS_SCHEMA = PostConceptListSchema.model_json_schema()

ADDITIONAL_CONCEPTS_USER_PROMPT = """
Generate more post concepts based on this feedback: {feedback_text}.

Make sure these are *different styles or takes* on the same idea — not entirely new ideas.

Each concept must be unique in its framing, tone, or approach while staying true to the selected idea and user context.

Follow the same JSON schema format for output.
"""

BRIEF_USER_PROMPT_TEMPLATE = """Create a detailed content brief using these selected concepts:

SELECTED CONCEPTS: {selected_concepts}

ALIGNMENT CONTEXT:
User Background: {user_dna}
Content History: {merged_posts}
Original Request: {user_input}

Develop a comprehensive brief that brings the concept to life as an engaging LinkedIn post.
"""


BRIEF_SYSTEM_PROMPT_TEMPLATE = """You are an expert LinkedIn content brief developer, specializing in transforming concepts into detailed, executable content strategies.

BRIEF DEVELOPMENT EXPERTISE:
- Converting high-level concepts into structured, actionable content plans
- Creating compelling narrative flows that maintain reader engagement
- Developing authentic hooks that align with professional voice and expertise
- Structuring content for optimal LinkedIn algorithm performance and reader experience

BRIEF CONSTRUCTION FRAMEWORK:
1. CONCEPT TRANSLATION: Transform the selected concept into a concrete content strategy
2. NARRATIVE ARCHITECTURE: Design a logical flow from hook to call-to-action
3. AUDIENCE OPTIMIZATION: Tailor messaging and examples for the target professional audience
4. ENGAGEMENT DESIGN: Structure content to encourage comments, shares, and meaningful interaction
5. AUTHENTICITY ASSURANCE: Ensure the brief reflects the user's genuine expertise and voice

CONTENT STRUCTURE PRINCIPLES:
- Opening Hook: Must align with concept style and create immediate engagement
- Value Delivery: Provide genuine insights, frameworks, or perspectives
- Evidence Integration: Include relevant examples, data, or case studies
- Practical Application: Offer actionable takeaways readers can implement
- Engagement Catalyst: End with questions or calls-to-action that invite response

BRIEF COMPONENTS FOCUS:
- Core Perspective: The unique angle that differentiates this content
- Key Messages: 3-5 primary points that support the perspective
- Supporting Evidence: Specific examples, data, or case studies to include
- Structural Flow: Logical progression from hook to conclusion
- Engagement Strategy: How to invite meaningful audience interaction

PROFESSIONAL ALIGNMENT:
- Match tone and complexity to the user's industry and seniority level
- Incorporate industry-specific language and references appropriately
- Ensure content pillar alignment with overall thought leadership strategy
- Consider the user's business objectives and audience expectations

OUTPUT SPECIFICATIONS:
- Create one comprehensive brief based on the selected concept(s)
- Set scheduled_date to null as specified
- Include 5-7 relevant hashtags that enhance discoverability
- Provide 2-3 hook options that match the concept's narrative style
- Respond only with valid JSON matching the schema

Respond strictly with the JSON output conforming to the schema: ```json\n{schema}\n```
"""


# Feedback Interpretation Schema and Prompts
USER_INPUT_INTERPRETATION_SYSTEM_PROMPT = """You are an expert content strategist specializing in LinkedIn content analysis. Your role is to interpret user requests for content creation and extract structured insights.

CORE RESPONSIBILITIES:
- Analyze user input to identify the main topic and content goals
- Determine the user's intended audience and messaging strategy
- Identify key angles and perspectives that align with their expertise
- Extract actionable content direction from ambiguous requests

ANALYSIS FRAMEWORK:
1. Topic Identification: What is the core subject matter?
2. Goal Assessment: What does the user want to achieve? (thought leadership, lead generation, engagement, education, etc.)
3. Angle Discovery: What unique perspectives or approaches are implied?
4. Audience Mapping: Who should this content reach and resonate with?
5. Message Extraction: What key points need to be communicated?

CONTEXT INTEGRATION RULES:
- Use User DNA to understand their expertise, industry position, and natural voice
- Reference recent posts only to avoid repetition and identify content gaps
- Maintain consistency with their established thought leadership themes
- Consider their professional goals and audience expectations

OUTPUT REQUIREMENTS:
- Respond only with valid JSON matching the provided schema
- Be specific and actionable in your interpretations
- Avoid generic or vague categorizations
- Focus on unique angles that differentiate from standard industry content
"""

USER_INPUT_INTERPRETATION_USER_PROMPT = """Analyze this content request:

USER REQUEST: {user_input}

CONTEXT:
User DNA: {user_dna}
Recent Posts: {merged_posts}

Provide a structured interpretation following the analysis framework.
"""

class UserInputInterpretationSchema(BaseModel):
    """Schema for interpreting user input."""
    core_topic: str = Field(..., description="The main topic or theme the user wants to explore")
    goals: List[str] = Field(..., description="List of specific goals or objectives identified from the input")
    key_angles: List[str] = Field(..., description="Potential angles or perspectives to explore")
    target_audience: List[str] = Field(..., description="Identified target audience segments")
    key_messages: List[str] = Field(..., description="Key messages or points to convey")
    
USER_INPUT_INTERPRETATION_SCHEMA = UserInputInterpretationSchema.model_json_schema()




class TargetAudienceSchema(BaseModel):
    """Target audience information for brief"""
    primary: str = Field(description="Primary target audience")
    secondary: Optional[str] = Field(None, description="Secondary target audience")


class StructureOutlineSchema(BaseModel):
    """Outline of post structure"""
    opening_hook: str = Field(description="Opening hook to grab attention")
    common_misconception: str = Field(description="Common misconception to address")
    core_perspective: str = Field(description="Core perspective to present")
    supporting_evidence: str = Field(description="Supporting evidence for perspective")
    practical_framework: str = Field(description="Practical framework or application")
    strategic_takeaway: str = Field(description="Strategic takeaway for reader")
    engagement_question: str = Field(description="Question to drive engagement")


class PostLengthSchema(BaseModel):
    """Target post length range"""
    min: int = Field(description="Minimum length")
    max: int = Field(description="Maximum length")

class ContentBriefSchema(BaseModel):
    """Detailed content brief based on selected concept (AI-generated)"""
    # uuid: str = Field(description="Unique identifier for the brief")
    title: str = Field(description="Brief title")
    scheduled_date: Optional[datetime] = Field(None, description="Scheduled date for the post in datetime format UTC TZ", format="date-time")
    content_pillar: str = Field(description="Content pillar category")
    target_audience: TargetAudienceSchema = Field(description="Target audience information")
    core_perspective: str = Field(description="Core perspective for the post")
    post_objectives: List[str] = Field(description="Objectives of the post")
    key_messages: List[str] = Field(description="Key messages to convey")
    evidence_and_examples: List[str] = Field(description="Supporting evidence and examples")
    tone_and_style: str = Field(description="Tone and style guidelines")
    structure_outline: StructureOutlineSchema = Field(description="Outline of post structure")
    suggested_hook_options: List[str] = Field(description="Suggested hook options")
    call_to_action: str = Field(description="Call to action")
    hashtags: List[str] = Field(description="Suggested hashtags")
    post_length: PostLengthSchema = Field(description="Target post length range")


BRIEF_LLM_OUTPUT_SCHEMA = ContentBriefSchema.model_json_schema()