from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Union



INITIAL_CONCEPTS_USER_PROMPT = """Pitch 4 content concepts for a LinkedIn post based on the selected idea and user context.

**Context:**
- Interpreted User Input: {interpreted_user_input}
- User DNA (use this to understand the individual's unique background, tone, and positioning): {user_dna}
- Recent User Posts (use this to avoid repetition and find fresh angles): {merged_posts}

**Task:**
Generate 4 distinct *post concepts* — these are *different ways* to approach or express the same idea. Think of these as narrative treatments, tonal variations, or strategic angles — not new ideas altogether.

Each concept should include:
- **Hook**: [A bold, concise, or curiosity-driven opener. It may pose a question, present a contradiction, or make a striking statement to lead the reader into the post.]
- **Message**: [2–3 sentences explaining the tone, perspective, and delivery approach. For example: a contrarian stance, personal story, tactical breakdown, future prediction, trend synthesis, or question-led framing.]

Ensure the concepts:
- Offer distinctly different styles or narrative approaches to the same core idea.
- Are aligned with the user’s field, voice, and target audience.

Respond ONLY with the JSON object matching the specified schema.
"""

INITIAL_CONCEPTS_SYSTEM_PROMPT = """
You are an expert LinkedIn content strategist. Based on the selected idea and user context, generate 4 differentiated *content concepts*.

These are NOT new ideas — they are different ways to write or frame the same idea. Think in terms of narrative styles, post structures, emotional tones, or positioning strategies.

Examples of concept styles: personal anecdote, tactical advice, thought leadership, contrarian view, data-backed insight, etc.

Respond strictly with the JSON output conforming to the schema: ```json\n{schema}\n```
"""


class PostConceptSchema(BaseModel):
    """Content concept schema for a single LinkedIn post concept."""
    concept_id: str = Field(description="Unique identifier for the concept")
    hook: str = Field(description="Attention-grabbing hook")
    message: str = Field(description="Main message of the concept")

class PostConceptListSchema(BaseModel):
    """List of post concepts generated by the LLM."""
    concepts: List[PostConceptSchema] = Field(description="List of post concepts")

CONCEPTS_SCHEMA = PostConceptListSchema.model_json_schema()

ADDITIONAL_CONCEPTS_USER_PROMPT = """
Generate 4 more post concepts based on this feedback: {feedback_text}.

Make sure these are *different styles or takes* on the same idea — not entirely new ideas.

Each concept must be unique in its framing, tone, or approach while staying true to the selected idea and user context.

Follow the same JSON schema format for output.
"""

BRIEF_USER_PROMPT_TEMPLATE = """Create a content brief for a LinkedIn post based on one of the selected concepts.

**Selected Concepts:**
{selected_concepts}

**User Context:**
- User DNA (use this to understand the individual's unique background, tone, and positioning): {user_dna}
- Recent User Posts (use this to ensure this brief takes a fresh and original direction): {merged_posts}

**User Input:**
- User Input: {user_input}

**Task:**
Develop a detailed content brief for a LinkedIn post using the selected concept. This brief should be shaped by the concept’s tone, structure, and perspective, and grounded in the user's expertise and goals.

Include:
- A clear and refined topic
- A hook/angle that matches the concept style (e.g., contrarian, story-driven, tactical)
- 3–5 key talking points that develop the message
- A CTA appropriate to the audience and concept
- 5–7 relevant hashtags

Make sure the brief is distinct from previous posts and suitable for the user's audience.

Respond ONLY with the JSON object matching the specified schema.
"""


BRIEF_SYSTEM_PROMPT_TEMPLATE = """
You are an expert LinkedIn content strategist. Based on the selected concept, user input, and context, create a content brief that brings this concept to life in the form of a compelling LinkedIn post.

Ensure originality, audience relevance, and consistency with the user's tone and expertise.

Respond strictly with the JSON output conforming to the schema: ```json\n{schema}\n```
"""


# Feedback Interpretation Schema and Prompts
USER_INPUT_INTERPRETATION_SYSTEM_PROMPT = """
You are an expert content strategist. Analyze the user's input text to understand their content needs and goals.
Respond with a structured interpretation that captures the key aspects of their request.
"""

USER_INPUT_INTERPRETATION_USER_PROMPT = """Analyze the following user input for content creation:

**User Input:**
{user_input}

**User Context:**
- User DNA (for understanding the user’s expertise, tone, and content themes): {user_dna}
- Recent Posts (to help avoid repetition and identify fresh directions): {merged_posts}

**Task:**
Interpret the user's input to determine:
1. The core topic/theme they want to explore
2. Specific content goals (e.g., share an opinion, attract leads, teach something)
3. Preferred angles or narrative perspectives
4. Target audience considerations (e.g., roles, industries, seniority)
5. Key messages they want to convey

Your output should help an LLM understand exactly what the user is trying to accomplish with their next post.

Respond with a structured JSON object matching the interpretation schema.
"""

class UserInputInterpretationSchema(BaseModel):
    """Schema for interpreting user input."""
    core_topic: str = Field(..., description="The main topic or theme the user wants to explore")
    goals: List[str] = Field(..., description="List of specific goals or objectives identified from the input")
    key_angles: List[str] = Field(..., description="Potential angles or perspectives to explore")
    target_audience: List[str] = Field(..., description="Identified target audience segments")
    key_messages: List[str] = Field(..., description="Key messages or points to convey")
    
USER_INPUT_INTERPRETATION_SCHEMA = UserInputInterpretationSchema.model_json_schema()