from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Union


INITIAL_IDEAS_USER_PROMPT = """Pitch 4 post ideas for LinkedIn posts based on the following documents:

**Context:**
- Initial Brief: {initial_brief}
- User DNA (use this for understanding the individual's unique background): {user_dna}
- Recent User Posts (use this for understanding the individual's recent posts and avoid repeating any previously disliked or used themes): {merged_posts}

**Task:**
Generate 4 distinct content ideas that could be developed into LinkedIn posts.

Each idea must:
- Be aligned with the **content pillar**, **objective**, and **target audience** defined in the Initial Brief.
- Avoid reusing angles, themes, or post structures from previous posts that may have been disliked.
- Present varied directions so the user can choose between contrasting ideas.

Each idea should be in the following structure:
- **Title:** A short, clear, headline-style summary of the idea.
- **Description:** A concise paragraph (2–4 sentences) explaining the idea, its tone, strategic angle, and how it connects to the user's expertise.

Respond ONLY with the JSON object matching the specified schema.
"""


INITIAL_IDEAS_SYSTEM_PROMPT = """
You are an expert LinkedIn content strategist.

Generate 4 original and varied content ideas for LinkedIn posts. The ideas must:
- Rely on the content pillar, objective, and audience from the provided brief
- Avoid reusing or referencing ideas that were previously disliked
- Present diverse, high-clarity directions using the title + description format

Respond strictly with the JSON output conforming to the schema: ```json\n{schema}\n```
"""

class PostIdeaSchema(BaseModel):
    """Content idea schema for a single LinkedIn post idea."""
    idea_id: str = Field(description="Unique identifier for the idea")
    title: str = Field(description="A clear, headline-style title summarizing the idea")
    description: str = Field(description="Short paragraph explaining the idea, including the strategic purpose and tone")

class PostIdeaListSchema(BaseModel):
    """List of post ideas generated by the LLM."""
    ideas: List[PostIdeaSchema] = Field(description="List of post ideas")


IDEAS_SCHEMA = PostIdeaListSchema.model_json_schema()

ADDITIONAL_IDEAS_USER_PROMPT = """Generate more content ideas based on the following feedback: {feedback_text}.

- Ensure the new ideas are **materially different** from previously generated ones.
- Continue to focus on the content pillar, objective, and target audience from the original brief.
- Avoid previously used titles, descriptions, or narrative framing.

Each idea should include:
- **Title:** A clear, headline-style name for the idea.
- **Description:** A short paragraph that explains the concept and its strategic use.

Respond using the same schema."""


BRIEF_USER_PROMPT_TEMPLATE = """Update the content brief based on the selected ideas.

**Selected Ideas:**
{selected_ideas}

**User Context:**
- User DNA (use this to infuse the brief with unique background and expertise): {user_dna}
- Recent User Posts (avoid echoing old ideas or content styles): {merged_posts}

**Initial Brief:**
- Initial Brief: {initial_brief}

**Task:**
Develop a refined content brief that expands on the selected ideas.

The brief should:
- Focus on the **specific content pillar**, **objective**, and **target audience** in the original brief.
- Ensure this idea is fresh and distinct from anything previously posted or disliked.
- Include: refined topic, hook, detailed key points, clear CTA, and hashtags.

Respond ONLY with the JSON object matching the specified schema."""


BRIEF_SYSTEM_PROMPT_TEMPLATE = """
You are an expert LinkedIn content strategist.

Use the selected ideas and user context to develop a **fresh, differentiated** content brief. It must:
- Follow the content pillar, objective, and target audience from the initial brief
- Avoid overlap with previous posts or rejected directions
- Be unique and implementation-ready

Respond strictly with the JSON output conforming to the schema: ```json\n{schema}\n```
"""
