from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Union



INITIAL_IDEAS_USER_PROMPT = """Pitch 4 post ideas for LinkedIn posts based on the following documents:

**Context:**
- Interpreted User Input (focus on user intent): {interpreted_user_input}
- User DNA (for understanding the individual's unique background, expertise, and content pillars): {user_dna}
- Recent User Posts (to avoid repetition and suggest new angles): {merged_posts}

**Task:**
Generate 4 high-quality, non-repetitive content ideas that align with the user’s professional field, expertise, and recent interests.
Each idea should include a:
- **Hook**: [A short, bold, or curiosity-generating statement that connects the user's background to a relevant insight or challenge.]
- **Angle**: [A 2–3 sentence explanation of the idea’s perspective, how it uses the user’s experience to shed light on a theme, and how it positions them (e.g., expert, innovator, leader).]

Ensure:
- Each idea explores a unique content direction or pillar.
- All ideas are clearly different from the user’s recent posts.

Respond ONLY with the JSON object matching the specified schema.
"""

INITIAL_IDEAS_SYSTEM_PROMPT = """
You are an expert LinkedIn content strategist. Based on the user’s interpreted input, content DNA, and past posts, generate 4 insightful and original content ideas. 
Ensure each idea aligns with the user’s field and avoids repeating previously used themes or formats.

Respond strictly with the JSON output conforming to the schema: ```json\n{schema}\n```
"""


class PostIdeaSchema(BaseModel):
    """Content idea schema for a single LinkedIn post idea."""
    idea_id: str = Field(description="Unique identifier for the idea")
    hook: str = Field(description="Attention-grabbing hook")
    message: str = Field(description="Main message of the idea")

class PostIdeaListSchema(BaseModel):
    """List of post ideas generated by the LLM."""
    ideas: List[PostIdeaSchema] = Field(description="List of post ideas")

IDEAS_SCHEMA = PostIdeaListSchema.model_json_schema()

ADDITIONAL_IDEAS_USER_PROMPT = """
Generate 4 additional content ideas based on this feedback: {feedback_text}.

**Constraints:**
- Do not repeat previous post topics or formats.
- Maintain alignment with the user's field, tone, and positioning.
- Use the same JSON schema format for output.
"""

BRIEF_USER_PROMPT_TEMPLATE = """Create a detailed content brief for a LinkedIn post based on the selected ideas.

**Selected Ideas:**
{selected_ideas}

**User Context:**
- User DNA (use this to understand the individual's background, voice, field of expertise, and content pillars): {user_dna}
- Recent User Posts (use this to avoid repetition and suggest original directions): {merged_posts}

**User Input:**
- User Input: {user_input}

**Task:**
Craft a comprehensive content brief for a new LinkedIn post. This brief should:
- Be inspired by the selected ideas
- Reflect the user’s unique positioning and content strategy
- Stay distinct from any recent post themes or formats

The brief must include:
- A refined topic
- A strong angle or hook
- A breakdown of 3–5 detailed key talking points
- A clear call to action relevant to the topic and audience
- A list of relevant hashtags (5–7)

Respond ONLY with the JSON object matching the specified schema.
"""


BRIEF_SYSTEM_PROMPT_TEMPLATE = """
You are an expert LinkedIn content strategist. Based on the selected idea, user input, and overall context, create a unique and detailed content brief for a new LinkedIn post.

Avoid repetition of themes, tone, or structure from recent posts, and ensure the content aligns with the user's field and content pillars.

Respond strictly with the JSON output conforming to the schema: ```json\n{schema}\n```
"""


# Feedback Interpretation Schema and Prompts
USER_INPUT_INTERPRETATION_SYSTEM_PROMPT = """
You are an expert content strategist. Analyze the user's input text to understand their content needs and goals.
Respond with a structured interpretation that captures the key aspects of their request.
"""

USER_INPUT_INTERPRETATION_USER_PROMPT = """Analyze the following user input for content creation:

**User Input:**
{user_input}

**User Context:**
- User DNA (for understanding the user’s expertise, tone, and content themes): {user_dna}
- Recent Posts (to help avoid repetition and identify fresh directions): {merged_posts}

**Task:**
Interpret the user's input to determine:
1. The core topic/theme they want to explore
2. Specific content goals (e.g., share an opinion, attract leads, teach something)
3. Preferred angles or narrative perspectives
4. Target audience considerations (e.g., roles, industries, seniority)
5. Key messages they want to convey

Your output should help an LLM understand exactly what the user is trying to accomplish with their next post.

Respond with a structured JSON object matching the interpretation schema.
"""


class UserInputInterpretationSchema(BaseModel):
    """Schema for interpreting user input."""
    core_topic: str = Field(..., description="The main topic or theme the user wants to explore")
    goals: List[str] = Field(..., description="List of specific goals or objectives identified from the input")
    key_angles: List[str] = Field(..., description="Potential angles or perspectives to explore")
    target_audience: List[str] = Field(..., description="Identified target audience segments")
    key_messages: List[str] = Field(..., description="Key messages or points to convey")
    
USER_INPUT_INTERPRETATION_SCHEMA = UserInputInterpretationSchema.model_json_schema()


