from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Union



INITIAL_CONCEPTS_USER_PROMPT = """Generate 4 post concepts for LinkedIn based on the selected idea and the following user context:

**Context:**
- Initial Brief (use this to understand the idea that we are expanding on, objective, and target audience): {initial_brief}
- User DNA (use this for understanding the individual's unique background): {user_dna}
- Recent User Posts (use this to avoid repeating ideas or tones used before): {merged_posts}

**Task:**
You’re not generating new ideas — you are expanding on **one chosen idea** by suggesting 4 different **concepts** or **creative treatments** for it.

Each concept is a different way to present the same core idea — for example:
- A contrarian take
- A storytelling version
- A data-driven insight post
- A how-to breakdown
- A trend-based post

Each concept should include:
- **Hook**: An attention-grabbing opener or framing that sets the tone.
- **Description**: A short paragraph explaining the take and how it differs (e.g., tone, format, positioning). Show how the concept still aligns with the content pillar, target audience, and strategic intent.

Make the variations clearly distinct so the user can choose the best expression of the core idea.

Respond ONLY with the JSON object matching the specified schema.
"""


INITIAL_CONCEPTS_SYSTEM_PROMPT = """
You are an expert LinkedIn content strategist.

Your task is to take a single idea and generate 4 distinct **concepts** — different ways the idea can be written or positioned for LinkedIn.

Each concept should:
- Be unique in tone, framing, or angle (e.g., storytelling, contrarian, trend-driven)
- Still align with the content pillar, target audience, and brief
- Include a hook and a short description

Respond strictly with the JSON output conforming to the schema: ```json\n{schema}\n```
"""


class PostConceptSchema(BaseModel):
    """Content concept schema for a single LinkedIn post concept."""
    concept_id: str = Field(description="Unique identifier for the concept")
    hook: str = Field(description="Attention-grabbing opening or idea framing")
    description: str = Field(description="Short paragraph explaining the concept, including tone and angle")

class PostConceptListSchema(BaseModel):
    """List of post concepts generated by the LLM."""
    concepts: List[PostConceptSchema] = Field(description="List of post concepts")


CONCEPTS_SCHEMA = PostConceptListSchema.model_json_schema()

ADDITIONAL_CONCEPTS_USER_PROMPT = """Generate more content concepts based on the following feedback: {feedback_text}.

Each concept should be a **different way to express the same core idea**, varying in tone, format, or narrative approach.

Make sure:
- New concepts are different from previous ones
- They still match the content brief, audience, and strategic direction
- Each includes a distinct hook and description

Respond using the same schema."""


BRIEF_USER_PROMPT_TEMPLATE = """Update the content brief based on the selected concepts.

**Selected Concepts:**
{selected_concepts}

**User Context:**
- User DNA (use this for understanding the individual's unique background and adding context to the brief): {user_dna}
- Recent User Posts (use this to avoid repetition): {merged_posts}

**Initial Brief:**
- Initial Brief: {initial_brief}

**Task:**
Build a detailed content brief based on the selected concept.

The brief must:
- Be faithful to the concept’s unique angle
- Fit the original content pillar, objective, and audience
- Be clearly differentiated from prior posts

Include: topic, angle/hook, key talking points, CTA, hashtags.

Respond ONLY with the JSON object matching the specified schema."""


BRIEF_SYSTEM_PROMPT_TEMPLATE = """
You are an expert LinkedIn content strategist.

Your task is to create a content brief that expands on a selected concept — a specific way to express a given idea.

The brief must:
- Build on the selected concept’s angle and framing
- Stay aligned with the content pillar, objective, and audience in the brief
- Include: topic, refined angle/hook, key points, CTA, and hashtags

Respond strictly with the JSON output conforming to the schema: ```json\n{schema}\n```
"""


